package ca.bc.mefm.resource;

import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;

import ca.bc.mefm.data.City;
import ca.bc.mefm.data.Comment;
import ca.bc.mefm.data.DataAccess;
import ca.bc.mefm.data.Practitioner;
import ca.bc.mefm.data.Province;
import ca.bc.mefm.data.Question;
import ca.bc.mefm.data.QuestionChoice;
import ca.bc.mefm.data.QuestionGroup;
import ca.bc.mefm.data.Specialty;
import ca.bc.mefm.data.User;
import ca.bc.mefm.data.UserRole;

/**
 * This end point is part of the scheme for initializing the database with the following entities:
 * 
 * <li>UserRole</li>
 * <li>User (for fixed pre-determined Admin users)</li>
 * <li>Specialty</li>
 * <li>Question/li>
 * <li>QuestionChoice</li>
 * <li>QuestionGroup</li>
 * <p>
 * The first request the client makes is to this end point. 
 * If the database is empty, the hard coded values defined within this class are written to the database. 
 *
 * @author Robert
 */
@Path("/initialize")
public class InitializationResource extends AbstractResource {

    /**
     * Trigger a check of the database content.
     * If the database is empty, it is seeded with the values defined in this class
     * @return 200 OK
     */
    @GET
    public Response initialize(){
        DataAccess da = new DataAccess();
        List<UserRole> list = da.getAll(UserRole.class);
        if (list.isEmpty()) {
        	// The database is empty, either because this is the first time the 
        	// application has been invoked, or the database has been emptied 
        	// using the Google App Engine admin console, with the intention of
        	// adding new entities
        	
        	roles.forEach((UserRole o) -> da.ofyPut(o));
        	users.forEach((User o) -> da.ofyPut(o));
        	specialties.forEach((Specialty o) -> da.ofyPut(o));
        	questionChoices.forEach((QuestionChoice o) -> da.ofyPut(o));
        	questionGroups.forEach((QuestionGroup o) -> da.ofyPut(o));
        	questions.forEach((Question o) -> da.ofyPut(o));
        	provinces.forEach((Province o) -> da.ofyPut(o));
        	
        	// TODO REmove kludge
        	practitioners.forEach((Practitioner o) -> da.ofyPut(o));
//        	comments.forEach((Comment o) -> da.ofyPut(o));
            
        	addCities(1L, namesBC, da);
            addCities(2L, namesAB, da);
            addCities(3L, namesSK, da);
            addCities(4L, namesMN, da);
            addCities(5L, namesON, da);
            addCities(6L, namesQU, da);
            addCities(7L, namesNB, da);
            addCities(8L, namesNS, da);
            addCities(9L, namesNFLD, da);
            addCities(10L, namesPEI, da);
            addCities(11L, namesNWT, da);
            addCities(12L, namesNU, da);
            addCities(13L, namesYU, da);

        }
        return responseNoContent();
    }
    
    // TODO Kludge
    List<Practitioner> practitioners = Arrays.asList(new Practitioner[]{
        new Practitioner(1L, "Doe",   	"Jane", "", "","",	"Canada","V6G-1W8","","", 5L, new Date(), new Date()),
        new Practitioner(2L, "Smith", 	"John", "", "","",	"Canada","V8V-4V9","","", 6L, new Date(), new Date()),
        new Practitioner(3L, "Brown",   "", 	"", "","",	"Canada","V9B-3R3","","", 5L, new Date(), new Date()),
        new Practitioner(4L, "Blue", 	"", 	"", "","",	"Canada","V9B-1H8","","", 6L, new Date(), new Date()),
        new Practitioner(5L, "Green",   "", 	"", "","",	"Canada","V9C-2W8","","", 5L, new Date(), new Date()),
        new Practitioner(6L, "Black",	"", 	"", "","",	"Canada","V8Z-1M8","","", 6L, new Date(), new Date()),
        new Practitioner(7L, "Red",   	"", 	"", "","",	"Canada","V8Y-2L3","","", 5L, new Date(), new Date()),
        new Practitioner(8L, "Purple", 	"", 	"", "","",	"Canada","V8P-5C2","","", 6L, new Date(), new Date()),
        new Practitioner(9L, "Bad",   	"", 	"", "","",	"Canada","bad-bad","","", 5L, new Date(), new Date()),
        new Practitioner(10L, "Thomas", "", 	"", "","",	"Canada","V7B-0V7","","", 6L, new Date(), new Date())
    });
    List<Comment> comments = Arrays.asList(new Comment[]{
    	new Comment(1L, null, 1L, 1L, new Date(), "He's an idiot", true),
    	new Comment(2L, 1L,   2L, 1L, new Date(), "Yes he is", true),
    	new Comment(3L, 1L,   1L, 1L, new Date(), "No he isn't", true),
    	new Comment(4L, null, 2L, 1L, new Date(), "I like him a lot", true),
    	new Comment(5L, 4L,   1L, 1L, new Date(), "So do I", true),
    	new Comment(6L, 4L,   2L, 1L, new Date(), "Me too!", true),
    	new Comment(7L, 4L,   1L, 1L, new Date(), "Me me me!", true),
    	
    	new Comment(8L, null, 2L, 2L, new Date(), "She's great", true),    	
    	new Comment(9L, 8L,   1L, 2L, new Date(), "She's great!", true)    	
    });
    
    
    /** Builds a city list for a specified province */
    private void addCities(Long provinceId, String[] cityNames, DataAccess da){
    	List<City> cities =	Stream.of(cityNames).map(cityName -> new City(provinceId, cityName)).collect(Collectors.toList());
    	da.ofyPut(cities);
    }

    
    List<UserRole> roles = Arrays.asList(new UserRole[]{
        new UserRole(1L, UserRole.TYPE_ACTIVE),
        new UserRole(2L, UserRole.TYPE_ADMINISTRATOR)
    });

    // Two built in accounts are created. The first is for the MEFM administrative user
    // responsible for "vetting" user comments.
    // The second is for a technical administrator. This is intended to support possible
    // future capabilities related to modification or updates to the database schema and/or 
    // modifications to the question definitions
    
    List<User> users = Arrays.asList(new User[]{
            new User(1L, "admin", "admin", "your-email-here", 2, new Date(), User.Status.ENABLED),
            new User(2L, "techadmin", "DumD0nald", "robert.t.toms@gmail.com", 3, new Date(), User.Status.ENABLED)
    });
    
    List<Specialty> specialties = Arrays.asList(new Specialty[]{
        new Specialty(1L, "Anaesthesia"),
        new Specialty(2L, "Cardiology"),
        new Specialty(3L, "Chiropody"),
        new Specialty(4L, "Clinical Immunology"),
        new Specialty(5L, "Dental"),
        new Specialty(6L, "Dietician"),
        new Specialty(7L, "Emergency Medicine"),
        new Specialty(8L, "Endocrinology"),
        new Specialty(9L, "Family and General Practice"),
        new Specialty(10L, "Gastroenterology"),
        new Specialty(11L, "Genetics"),
        new Specialty(12L, "Geriatrics"),
        new Specialty(13L, "Haematology "),
        new Specialty(14L, "Internal Medicine"),
        new Specialty(15L, "Kinesiology"),
        new Specialty(16L, "Midwife"),
        new Specialty(17L, "Neurology"),
        new Specialty(18L, "Nuclear Medicine "),
        new Specialty(19L, "Nurse Practioner"),
        new Specialty(20L, "Obstetrics and Gynaecology"),
        new Specialty(21L, "Occupational Therapy"),
        new Specialty(22L, "Ophthalmology "),
        new Specialty(23L, "Optometry"),
        new Specialty(24L, "Osteopathy"),
        new Specialty(25L, "Otolaryngology "),
        new Specialty(26L, "Paediatrics"),
        new Specialty(27L, "Pathology "),
        new Specialty(28L, "Physical Medicine "),
        new Specialty(29L, "Physiotherapy"),
        new Specialty(30L, "Psychiatry"),
        new Specialty(31L, "Psychology"),
        new Specialty(32L, "Respiratory Diseases "),
        new Specialty(33L, "Rheumatology "),
        new Specialty(34L, "Urology "),
        new Specialty(35L, "Naturopath"),
        new Specialty(36L, "Integrative Medicine"),
        new Specialty(37L, "Chiropractor"),
        new Specialty(38L, "Massage Therapy"),
        new Specialty(39L, "Traditional Chinese Medicine"),
        new Specialty(41L, "Osteopath"),
        new Specialty(42L, "Acupuncture"),
        new Specialty(43L, "Homeopath"),
        new Specialty(44L, "Other Alternative Profession")
    });

    List<QuestionChoice> questionChoices = Arrays.asList(new QuestionChoice[]{
        new QuestionChoice(1L, "Never heard of it",            1L),
        new QuestionChoice(2L, "Knows very little",            1L),
        new QuestionChoice(3L, "Moderate knowledge",           1L),
        new QuestionChoice(4L, "Very knowledgeable",           1L),
        new QuestionChoice(5L, "Expert",                       1L),
        new QuestionChoice(6L, "Very bad",                     2L),
        new QuestionChoice(7L, "Bad",                          2L),
        new QuestionChoice(8L, "Acceptable",                   2L),
        new QuestionChoice(9L, "Good",                         2L),
        new QuestionChoice(10L, "Excellent ",                  2L),
        new QuestionChoice(11L, "Very unhelpful",              3L),
        new QuestionChoice(12L, "Unhelpful",                   3L),
        new QuestionChoice(13L, "Acceptable",                  3L),
        new QuestionChoice(14L, "Helpful",                     3L),
        new QuestionChoice(15L, "Very helpful",                3L),
        new QuestionChoice(16L, "Very unwilling",              4L),
        new QuestionChoice(17L, "Unwilling",                   4L),
        new QuestionChoice(18L, "Unsure",                      4L),
        new QuestionChoice(19L, "Will consider",               4L),
        new QuestionChoice(20L, "Willing",                     4L),
        new QuestionChoice(21L, "Made things worse",           5L),
        new QuestionChoice(22L, "Unhelpful",                   5L),
        new QuestionChoice(23L, "Acceptable",                  5L),
        new QuestionChoice(24L, "Effective",                   5L),
        new QuestionChoice(25L, "Very effective",              5L),
        new QuestionChoice(26L, "Very unhelpful / rude",       6L),
        new QuestionChoice(27L, "Unhelpful",                   6L),
        new QuestionChoice(28L, "Acceptable",                  6L),
        new QuestionChoice(29L, "Helpful",                     6L),
        new QuestionChoice(30L, "Very helpful",                6L),
        new QuestionChoice(31L, "Always running very behind",  7L),
        new QuestionChoice(32L, "Not punctual",                7L),
        new QuestionChoice(33L, "Often not punctual",          7L),
        new QuestionChoice(34L, "Mostly punctual",             7L),
        new QuestionChoice(35L, "Always punctual",             7L),
        new QuestionChoice(36L, "Less than $50",               8L),
        new QuestionChoice(37L, "$50 - $75",                   8L),
        new QuestionChoice(38L, "$75 - $100",                  8L),
        new QuestionChoice(39L, "$100 - $150",                 8L),
        new QuestionChoice(40L, "Over $150",                   8L),
        new QuestionChoice(41L, "Strongly do not recommend",   9L),
        new QuestionChoice(42L, "Possibly recommend if none other is available", 9L),
        new QuestionChoice(43L, "Not sure",                    9L),
        new QuestionChoice(44L, "Would recommend",             9L),
        new QuestionChoice(45L, "Would strongly recommend",    9L)
	});

    List<QuestionGroup> questionGroups = Arrays.asList(new QuestionGroup[] {
        new QuestionGroup(1L, "1 Did you see this practioner for (check which apply)"),
        new QuestionGroup(2L, "2 What is the practitioner's level of knowledge about"),
        new QuestionGroup(3L, "3 How familiar is the practitioner with any of the consensus criteria for ME?"),
        new QuestionGroup(4L, "4 How familiar is the practitioner with any of the consensus criteria for fibromyalgia?"),
        new QuestionGroup(5L, "5 Did the practitioner prescribe graded exercise therapy (GET) as treatment"),
        new QuestionGroup(6L, "6 Did the practitioner prescribe cognitive behaviour therapy (CBT) as treatment for the illness, rather than a management tool, for"),
        new QuestionGroup(7L, "8 Regarding a treatment plan, how helpful was the practitioner with"),
        new QuestionGroup(8L, "15 How accessible is the practitioner's office?")
        });

    List<Question> questions = Arrays.asList(new Question[] {
        new Question( 1L,  1,  null,  1L,     Question.Type.YES_NO,         "ME?"),
        new Question( 2L,  2,  null,  1L,     Question.Type.YES_NO,         "FM?"),
        new Question( 3L,  3,  1L,    2L,     Question.Type.SINGLE_CHOICE,  "ME?"),
        new Question( 4L,  4,  1L,    2L,     Question.Type.SINGLE_CHOICE,  "FM?"),
        new Question( 5L,  5,  1L,    3L,     Question.Type.SINGLE_CHOICE,  "Canadian Consensus Criteria, (2003)"),
        new Question( 6L,  6,  1L,    3L,     Question.Type.SINGLE_CHOICE,  "International Consensus Criteria, (2011)"),
        new Question( 7L,  7,  1L,    3L,     Question.Type.SINGLE_CHOICE,  "Myalgic Encephalomyelitis/Chronic Fatigue Syndrome Diagnosis and Management in Young People: A Primer (2017)"),
        new Question( 8L,  8,  1L,    3L,     Question.Type.SINGLE_CHOICE,  "Beyond Myalgic Encephalomyelitis/Chronic Fatigue Syndrome: Redefining an Illness, (2015)"),
        new Question( 9L,  9,  1L,    4L,     Question.Type.SINGLE_CHOICE,  "Fibromyalgia Syndrome: Canadian Clinical Working Case Definition, Diagnostic and Treatment Protocols. A Consensus Document"),
        new Question( 10L, 10, 1L,    4L,     Question.Type.SINGLE_CHOICE,  "2010 American College of Rheumatology (ACR) Preliminary Diagnostic Criteria for Fibromyalgia: Overview"),
        new Question( 11L, 11, 1L,    5L,     Question.Type.YES_NO,         "ME?"),
        new Question( 12L, 12, null,  5L,     Question.Type.YES_NO,         "FM?"),
        new Question( 13L, 13, null,  6L,     Question.Type.YES_NO,         "ME?"),
        new Question( 14L, 14, null,  6L,     Question.Type.YES_NO,         "FM?"),
        new Question( 15L, 15, 2L,    null,   Question.Type.SINGLE_CHOICE,  "7 How is the practitioner's bedside manner at your visit?"),
        new Question( 16L, 16, 3L,    7L,     Question.Type.SINGLE_CHOICE,  "Developing a treatment plan? "),
        new Question( 17L, 17, 3L,    7L,     Question.Type.SINGLE_CHOICE,  "Overseeing a treatment plan?"),
        new Question( 18L, 18, 3L,    null,   Question.Type.SINGLE_CHOICE,  "9 How willing is the practitioner to read information you bring to the consult?"),
        new Question( 19L, 19, 4L,    null,   Question.Type.SINGLE_CHOICE,  "10 How willing is the practitioner to prescribe alternative or off-label treatments?"),
        new Question( 20L, 20, 5L,    null,   Question.Type.SINGLE_CHOICE,  "11 How effective was is practitioner at helping to manage pain issues?"),
        new Question( 21L, 21, 3L,    null,   Question.Type.SINGLE_CHOICE,  "12 How helpful was the practitioner with completing insurance/disability forms?"),
        new Question( 22L, 22, null,  null,   Question.Type.YES_NO,         "13 Did the practitioner offer referrals to other practitioner or clinics?"),
        new Question( 23L, 23, 6L,    null,   Question.Type.SINGLE_CHOICE,  "14 How helpful is the practitioner's staff"),
        new Question( 24L, 24, null,  8L,     Question.Type.YES_NO,         "Wheelchair accessible"),
        new Question( 25L, 25, null,  8L,     Question.Type.YES_NO,         "Handicap parking available"),
        new Question( 26L, 26, null,  8L,     Question.Type.YES_NO,         "Public transport close by"),
        new Question( 27L, 27, null,  8L,     Question.Type.YES_NO,         "Elevator near office"),
        new Question( 28L, 28, 7L,    null,   Question.Type.SINGLE_CHOICE,  "16 How punctual was the practitioner?"),
        new Question( 29L, 29, null,  null,   Question.Type.YES_NO,         "17 Did the practitioner offer you follow ups and/or continuous support?"),
        new Question( 30L, 30, null,  null,   Question.Type.YES_NO,         "18 Was your visit with the practitioner's service covered by MSP?"),
        new Question( 31L, 31, 8L,    null,   Question.Type.SINGLE_CHOICE,  "19 If answer to Q.18 is NO, what is the practitioner's consult fee?"),
        new Question( 32L, 32, 9L,    null,   Question.Type.SINGLE_CHOICE,  "20 How likely are you to recommend this practitioner?")
        });

    List<Province> provinces = Arrays.asList(new Province[]{
            new Province(1L, "British Columbia", "BC"),
            new Province(2L, "Alberta", "AB"),
            new Province(3L, "Saskatchewan", "SK"),
            new Province(4L, "Manitoba", "MN"),
            new Province(5L, "Ontario", "ON"),
            new Province(6L, "Quebec", "QU"),
            new Province(7L, "New Brunswick", "NB"),
            new Province(8L, "Nova Scotia", "NS"),
            new Province(9L, "Newfoundland", "NFLD"),
            new Province(10L, "Prince Edward Island", "PEI"),
            new Province(11L, "Northwest Territories", "NWT"),
            new Province(12L, "Nunavut", "NU"),
            new Province(13L, "Yukon", "YU")
        });
    
    static String[] namesBC = new String[]{
    		"Abbotsford",
    		"Armstrong",
    		"Burnaby",
    		"Campbell River",
    		"Castlegar",
    		"Chilliwack",
    		"Colwood",
    		"Coquitlam",
    		"Courtenay",
    		"Cranbrook",
    		"Dawson Creek",
    		"Delta",
    		"Duncan",
    		"Enderby",
    		"Fernie",
    		"Fort St. John",
    		"Grand Forks",
    		"Greenwood",
    		"Kamloops",
    		"Kelowna",
    		"Kimberley",
    		"Langford",
    		"Langley",
    		"Maple Ridge",
    		"Merritt",
    		"Nanaimo",
    		"Nelson",
    		"New Westminster",
    		"North Vancouver",
    		"Parksville",
    		"Penticton",
    		"Pitt Meadows",
    		"Port Alberni",
    		"Port Coquitlam",
    		"Port Moody",
    		"Powell River",
    		"Prince George",
    		"Prince Rupert",
    		"Quesnel",
    		"Revelstoke",
    		"Richmond",
    		"Rossland",
    		"Salmon Arm",
    		"Surrey",
    		"Terrace",
    		"Trail",
    		"Vancouver",
    		"Vernon",
    		"Victoria",
    		"West Kelowna",
    		"White Rock",
    		"Williams Lake",
    		"100 Mile House",
    		"Barriere",
    		"Central Saanich",
    		"Chetwynd",
    		"Clearwater",
    		"Coldstream",
    		"Elkford",
    		"Esquimalt",
    		"Fort St. James",
    		"Highlands",
    		"Hope",
    		"Houston",
    		"Hudson's Hope",
    		"Invermere",
    		"Kent",
    		"Kitimat",
    		"Lake Country",
    		"Langley",
    		"Lantzville",
    		"Lillooet",
    		"Logan Lake",
    		"Mackenzie",
    		"Metchosin",
    		"Mission",
    		"New Hazelton",
    		"North Cowichan",
    		"North Saanich",
    		"North Vancouver",
    		"Northern Rockies",
    		"Oak Bay",
    		"Peachland",
    		"Port Edward",
    		"Port Hardy",
    		"Saanich",
    		"Sechelt",
    		"Sicamous",
    		"Sooke",
    		"Spallumcheen",
    		"Sparwood",
    		"Squamish",
    		"Stewart",
    		"Summerland",
    		"Taylor",
    		"Tofino",
    		"Tumbler Ridge",
    		"Ucluelet",
    		"Vanderhoof",
    		"Wells",
    		"West Vancouver",
    		"Sechelt Indian Government District",
    		"Bowen Island",
    		"Jumbo Glacier",
    		"Sun Peaks",
    		"Whistler",
    		"Comox",
    		"Creston",
    		"Gibsons",
    		"Golden",
    		"Ladysmith",
    		"Lake Cowichan",
    		"Oliver",
    		"Osoyoos",
    		"Port McNeill",
    		"Princeton",
    		"Qualicum Beach",
    		"Sidney",
    		"Smithers",
    		"View Royal",
    		"Alert Bay",
    		"Anmore",
    		"Ashcroft",
    		"Belcarra",
    		"Burns Lake",
    		"Cache Creek",
    		"Canal Flats",
    		"Chase",
    		"Clinton",
    		"Cumberland",
    		"Fraser Lake",
    		"Fruitvale",
    		"Gold River",
    		"Granisle",
    		"Harrison Hot Springs",
    		"Hazelton",
    		"Kaslo",
    		"Keremeos",
    		"Lions Bay",
    		"Lumby",
    		"Lytton",
    		"Masset",
    		"McBride",
    		"Midway",
    		"Montrose",
    		"Nakusp",
    		"New Denver",
    		"Pemberton",
    		"Port Alice",
    		"Port Clements",
    		"Pouce Coupe",
    		"Queen Charlotte",
    		"Radium Hot Springs",
    		"Salmo",
    		"Sayward",
    		"Silverton",
    		"Slocan",
    		"Tahsis",
    		"Telkwa",
    		"Valemount",
    		"Warfield",
    		"Zeballos"};

    		String[] namesAB = new String[]{
    		"Acme",
    		"Airdrie",
    		"Alberta Beach",
    		"Alix",
    		"Alliance",
    		"Amisk",
    		"Andrew",
    		"Argentia Beach",
    		"Arrowwood",
    		"Athabasca",
    		"Banff",
    		"Barnwell",
    		"Barons",
    		"Barrhead",
    		"Bashaw",
    		"Bassano",
    		"Bawlf",
    		"Beaumont",
    		"Beaverlodge",
    		"Beiseker",
    		"Bentley",
    		"Berwyn",
    		"Betula Beach",
    		"Big Valley",
    		"Birch Cove",
    		"Birchcliff",
    		"Bittern Lake",
    		"Black Diamond",
    		"Blackfalds",
    		"Bon Accord",
    		"Bondiss",
    		"Bonnyville",
    		"Bonnyville Beach",
    		"Bow Island",
    		"Bowden",
    		"Boyle",
    		"Breton",
    		"Brooks",
    		"Bruderheim",
    		"Burnstick Lake",
    		"Calgary",
    		"Calmar",
    		"Camrose",
    		"Canmore",
    		"Carbon",
    		"Cardston",
    		"Carmangay",
    		"Caroline",
    		"Carstairs",
    		"Castle Island",
    		"Castor",
    		"Cereal",
    		"Champion",
    		"Chauvin",
    		"Chestermere",
    		"Chipman",
    		"Claresholm",
    		"Clive",
    		"Clyde",
    		"Coaldale",
    		"Coalhurst",
    		"Cochrane",
    		"Cold Lake",
    		"Consort",
    		"Coronation",
    		"Coutts",
    		"Cowley",
    		"Cremona",
    		"Crossfield",
    		"Crystal Springs",
    		"Czar",
    		"Daysland",
    		"Delburne",
    		"Delia",
    		"Devon",
    		"Dewberry",
    		"Didsbury",
    		"Donalda",
    		"Donnelly",
    		"Drayton Valley",
    		"Drumheller",
    		"Duchess",
    		"Eckville",
    		"Edberg",
    		"Edgerton",
    		"Edmonton",
    		"Edson",
    		"Elk Point",
    		"Elnora",
    		"Empress",
    		"Fairview",
    		"Falher",
    		"Ferintosh",
    		"Foremost",
    		"Forestburg",
    		"Fort Macleod",
    		"Fort Saskatchewan",
    		"Fox Creek",
    		"Gadsby",
    		"Ghost Lake",
    		"Gibbons",
    		"Girouxville",
    		"Glendon",
    		"Glenwood",
    		"Golden Days",
    		"Grande Prairie",
    		"Grandview",
    		"Granum",
    		"Grimshaw",
    		"Gull Lake",
    		"Half Moon Bay",
    		"Halkirk",
    		"Hanna",
    		"Hardisty",
    		"Hay Lakes",
    		"Heisler",
    		"High Level",
    		"High Prairie",
    		"High River",
    		"Hill Spring",
    		"Hines Creek",
    		"Hinton",
    		"Holden",
    		"Horseshoe Bay",
    		"Hughenden",
    		"Hussar",
    		"Hythe",
    		"Innisfail",
    		"Innisfree",
    		"Irma",
    		"Irricana",
    		"Island Lake South",
    		"Island Lake",
    		"Itaska Beach",
    		"Jarvis Bay",
    		"Kapasiwin",
    		"Killam",
    		"Kitscoty",
    		"Lacombe",
    		"Lakeview",
    		"Lamont",
    		"Larkspur",
    		"Leduc",
    		"Legal",
    		"Lethbridge",
    		"Linden",
    		"Lloydminster",
    		"Lomond",
    		"Longview",
    		"Lougheed",
    		"Magrath",
    		"Ma-Me-O Beach",
    		"Manning",
    		"Mannville",
    		"Marwayne",
    		"Mayerthorpe",
    		"McLennan",
    		"Medicine Hat",
    		"Mewatha Beach",
    		"Milk River",
    		"Millet",
    		"Milo",
    		"Morinville",
    		"Morrin",
    		"Mundare",
    		"Munson",
    		"Myrnam",
    		"Nampa",
    		"Nakamun Park",
    		"Nanton",
    		"Nobleford",
    		"Norglenwold",
    		"Norris Beach",
    		"Okotoks",
    		"Olds",
    		"Onoway",
    		"Oyen",
    		"Paradise Valley",
    		"Parkland Beach",
    		"Peace River",
    		"Pelican Narrows",
    		"Penhold",
    		"Picture Butte",
    		"Pincher Creek",
    		"Point Alison",
    		"Ponoka",
    		"Poplar Bay",
    		"Provost",
    		"Rainbow Lake",
    		"Raymond",
    		"Red Deer",
    		"Redcliff",
    		"Redwater",
    		"Rimbey",
    		"Rochon Sands",
    		"Rocky Mountain House",
    		"Rockyford",
    		"Rosalind",
    		"Rosemary",
    		"Ross Haven",
    		"Rycroft",
    		"Ryley",
    		"Sandy Beach",
    		"Seba Beach",
    		"Sedgewick",
    		"Sexsmith",
    		"Silver Beach",
    		"Silver Sands",
    		"Slave Lake",
    		"Smoky Lake",
    		"South Baptiste",
    		"South View",
    		"Spirit River",
    		"Spring Lake",
    		"Spruce Grove",
    		"St. Albert",
    		"St. Paul",
    		"Standard",
    		"Stavely",
    		"Stettler",
    		"Stirling",
    		"Stony Plain",
    		"Strathmore",
    		"Sunbreaker Cove",
    		"Sundance Beach",
    		"Sundre",
    		"Sunrise Beach",
    		"Sunset Beach",
    		"Sunset Point",
    		"Swan Hills",
    		"Sylvan Lake",
    		"Taber",
    		"Thorsby",
    		"Three Hills",
    		"Tofield",
    		"Trochu",
    		"Turner Valley",
    		"Two Hills",
    		"Val Quentin",
    		"Valleyview",
    		"Vauxhall",
    		"Vegreville",
    		"Vermilion",
    		"Veteran",
    		"Viking",
    		"Vilna",
    		"Vulcan",
    		"Wabamun",
    		"Wainwright",
    		"Waiparous",
    		"Warburg",
    		"Warner",
    		"Waskatenau",
    		"Wembley",
    		"West Baptiste",
    		"West Cove",
    		"Westlock",
    		"Wetaskiwin",
    		"Whispering Hills",
    		"White Sands",
    		"Whitecourt",
    		"Yellowstone",
    		"Youngstown"};

    		String[] namesSK = new String[]{
    		"Abbey",
    		"Aberdeen",
    		"Abernethy",
    		"Alameda",
    		"Albertville",
    		"Alice Beach",
    		"Alida",
    		"Allan",
    		"Alvena",
    		"Annaheim",
    		"Aquadeo",
    		"Arborfield",
    		"Archerwill",
    		"Arcola",
    		"Arran",
    		"Asquith",
    		"Assiniboia",
    		"Atwater",
    		"Avonlea",
    		"Aylesbury",
    		"Aylsham",
    		"Balcarres",
    		"Balgonie",
    		"Bangor",
    		"Battleford",
    		"Beatty",
    		"Beaver Flat",
    		"Beechy",
    		"Belle Plaine",
    		"Bengough",
    		"Bethune",
    		"Bienfait",
    		"Big River",
    		"Big Shell",
    		"Biggar",
    		"Birch Hills",
    		"Bird's Point",
    		"Bjorkdale",
    		"Bladworth",
    		"Blaine Lake",
    		"Borden",
    		"Bracken",
    		"Bradwell",
    		"Bredenbury",
    		"Briercrest",
    		"Broadview",
    		"Brock",
    		"Broderick",
    		"Brownlee",
    		"Bruno",
    		"B-Say-Tah",
    		"Buchanan",
    		"Buena Vista",
    		"Bulyea",
    		"Burstall",
    		"Cabri",
    		"Cadillac",
    		"Calder",
    		"Candle Lake",
    		"Canora",
    		"Canwood",
    		"Carievale",
    		"Carlyle",
    		"Carmichael",
    		"Carnduff",
    		"Caronport",
    		"Carrot River",
    		"Central Butte",
    		"Ceylon",
    		"Chamberlain",
    		"Chaplin",
    		"Chitek Lake",
    		"Choiceland",
    		"Chorney Beach",
    		"Christopher Lake",
    		"Churchbridge",
    		"Clavet",
    		"Climax",
    		"Cochin",
    		"Coderre",
    		"Codette",
    		"Coleville",
    		"Colonsay",
    		"Conquest",
    		"Consul",
    		"Coronach",
    		"Coteau Beach",
    		"Craik",
    		"Craven",
    		"Creelman",
    		"Cudworth",
    		"Cupar",
    		"Cut Knife",
    		"Dafoe",
    		"Dalmeny",
    		"Davidson",
    		"Debden",
    		"Delisle",
    		"Denholm",
    		"Denzil",
    		"Dilke",
    		"Dinsmore",
    		"Disley",
    		"Dodsland",
    		"Dorintosh",
    		"Drake",
    		"Drinkwater",
    		"Dubuc",
    		"Duck Lake",
    		"Duff",
    		"Dundurn",
    		"Duval",
    		"Dysart",
    		"Earl Grey",
    		"Eastend",
    		"Eatonia",
    		"Ebenezer",
    		"Echo Bay",
    		"Edam",
    		"Edenwold",
    		"Elbow",
    		"Elfros",
    		"Elrose",
    		"Endeavour",
    		"Englefeld",
    		"Ernfold",
    		"Esterhazy",
    		"Estevan",
    		"Eston",
    		"Etters Beach",
    		"Eyebrow",
    		"Fairlight",
    		"Fenwood",
    		"Fillmore",
    		"Findlater",
    		"Flaxcombe",
    		"Fleming",
    		"Flin Flon",
    		"Foam Lake",
    		"Forget",
    		"Fort Qu'Appelle",
    		"Fort San",
    		"Fosston",
    		"Fox Valley",
    		"Francis",
    		"Frobisher",
    		"Frontier",
    		"Gainsborough",
    		"Gerald",
    		"Glaslyn",
    		"Glen Ewen",
    		"Glen Harbour",
    		"Glenavon",
    		"Glenside",
    		"Golden Prairie",
    		"Goodeve",
    		"Goodsoil",
    		"Goodwater",
    		"Govan",
    		"Grand Coulee",
    		"Grandview Beach",
    		"Gravelbourg",
    		"Grayson",
    		"Greig Lake",
    		"Grenfell",
    		"Gull Lake",
    		"Hafford",
    		"Hague",
    		"Halbrite",
    		"Hanley",
    		"Harris",
    		"Hawarden",
    		"Hazenmore",
    		"Hazlet",
    		"Hepburn",
    		"Herbert",
    		"Heward",
    		"Hodgeville",
    		"Holdfast",
    		"Hubbard",
    		"Hudson Bay",
    		"Humboldt",
    		"Hyas",
    		"Imperial",
    		"Indian Head",
    		"Invermay",
    		"Island View",
    		"Ituna",
    		"Jansen",
    		"Kamsack",
    		"Kannata Valley",
    		"Katepwa",
    		"Keeler",
    		"Kelliher",
    		"Kelvington",
    		"Kenaston",
    		"Kendal",
    		"Kennedy",
    		"Kenosee Lake",
    		"Kerrobert",
    		"Killaly",
    		"Kincaid",
    		"Kindersley",
    		"Kinistino",
    		"Kinley",
    		"Kipling",
    		"Kisbey",
    		"Kivimaa-Moonlight Bay",
    		"Krydor",
    		"Kyle",
    		"Lafleche",
    		"Laird",
    		"Lake Alma",
    		"Lake Lenore",
    		"Lampman",
    		"Lancer",
    		"Landis",
    		"Lang",
    		"Langenburg",
    		"Langham",
    		"Lanigan",
    		"Lashburn",
    		"Leader",
    		"Leask",
    		"Lebret",
    		"Lemberg",
    		"Leoville",
    		"Leross",
    		"Leroy",
    		"Leslie Beach",
    		"Lestock",
    		"Liberty",
    		"Limerick",
    		"Lintlaw",
    		"Lipton",
    		"Lloydminster",
    		"Loon Lake",
    		"Loreburn",
    		"Love",
    		"Lucky Lake",
    		"Lumsden",
    		"Lumsden Beach",
    		"Luseland",
    		"Macklin",
    		"MacNutt",
    		"Macoun",
    		"Macrorie",
    		"Maidstone",
    		"Major",
    		"Makwa",
    		"Manitou Beach",
    		"Mankota",
    		"Manor",
    		"Maple Creek",
    		"Marcelin",
    		"Marengo",
    		"Margo",
    		"Markinch",
    		"Marquis",
    		"Marsden",
    		"Marshall",
    		"Martensville",
    		"Maryfield",
    		"Maymont",
    		"McLean",
    		"McTaggart",
    		"Meacham",
    		"Meadow Lake",
    		"Meath Park",
    		"Medstead",
    		"Melfort",
    		"Melville",
    		"Melville Beach",
    		"Mendham",
    		"Meota",
    		"Mervin",
    		"Metinota",
    		"Midale",
    		"Middle Lake",
    		"Milden",
    		"Milestone",
    		"Minton",
    		"Mistatim",
    		"Mistusinne",
    		"Montmartre",
    		"Moose Jaw",
    		"Moosomin",
    		"Morse",
    		"Mortlach",
    		"Mossbank",
    		"Muenster",
    		"Naicam",
    		"Neilburg",
    		"Netherhill",
    		"Neudorf",
    		"Neville",
    		"Nipawin",
    		"Nokomis",
    		"Norquay",
    		"North Battleford",
    		"North Grove",
    		"North Portal",
    		"Odessa",
    		"Ogema",
    		"Osage",
    		"Osler",
    		"Outlook",
    		"Oxbow",
    		"Paddockwood",
    		"Pangman",
    		"Paradise Hill",
    		"Parkside",
    		"Paynton",
    		"Pebble Baye",
    		"Pelican Pointe",
    		"Pelly",
    		"Pennant",
    		"Pense",
    		"Perdue",
    		"Pierceland",
    		"Pilger",
    		"Pilot Butte",
    		"Pleasantdale",
    		"Plenty",
    		"Plunkett",
    		"Ponteix",
    		"Porcupine Plain",
    		"Preeceville",
    		"Prelate",
    		"Prince Albert",
    		"Prud'homme",
    		"Punnichy",
    		"Qu'Appelle",
    		"Quill Lake",
    		"Quinton",
    		"Radisson",
    		"Radville",
    		"Rama",
    		"Raymore",
    		"Redvers",
    		"Regina Beach",
    		"Regina",
    		"Rhein",
    		"Richard",
    		"Richmound",
    		"Ridgedale",
    		"Riverhurst",
    		"Rocanville",
    		"Roche Percee",
    		"Rockglen",
    		"Rose Valley",
    		"Rosetown",
    		"Rosthern",
    		"Rouleau",
    		"Ruddell",
    		"Rush Lake",
    		"Saltcoats",
    		"Saskatchewan Beach",
    		"Saskatoon",
    		"Sceptre",
    		"Scott",
    		"Sedley",
    		"Semans",
    		"Senlac",
    		"Shamrock",
    		"Shaunavon",
    		"Sheho",
    		"Shell Lake",
    		"Shellbrook",
    		"Shields",
    		"Silton",
    		"Simpson",
    		"Sintaluta",
    		"Smeaton",
    		"Smiley",
    		"South Lake",
    		"Southey",
    		"Spalding",
    		"Speers",
    		"Spiritwood",
    		"Springside",
    		"Spy Hill",
    		"St. Benedict",
    		"St. Brieux",
    		"St. Gregor",
    		"St. Louis",
    		"St. Walburg",
    		"Star City",
    		"Stenen",
    		"Stewart Valley",
    		"Stockholm",
    		"Storthoaks",
    		"Stoughton",
    		"Strasbourg",
    		"Strongfield",
    		"Sturgis",
    		"Success",
    		"Sun Valley",
    		"Sunset Cove",
    		"Swift Current",
    		"Tantallon",
    		"Tessier",
    		"Theodore",
    		"Thode",
    		"Tisdale",
    		"Tobin Lake",
    		"Togo",
    		"Tompkins",
    		"Torquay",
    		"Tramping Lake",
    		"Tribune",
    		"Tugaske",
    		"Turtleford",
    		"Tuxford",
    		"Unity",
    		"Val Marie",
    		"Valparaiso",
    		"Vanguard",
    		"Vanscoy",
    		"Vibank",
    		"Viscount",
    		"Vonda",
    		"Wadena",
    		"Wakaw",
    		"Wakaw Lake",
    		"Waldeck",
    		"Waldheim",
    		"Waldron",
    		"Wapella",
    		"Warman",
    		"Waseca",
    		"Watrous",
    		"Watson",
    		"Wawota",
    		"Webb",
    		"Wee Too Beach",
    		"Weekes",
    		"Weirdale",
    		"Weldon",
    		"Welwyn",
    		"West End",
    		"Weyburn",
    		"White City",
    		"White Fox",
    		"Whitewood",
    		"Wilcox",
    		"Wilkie",
    		"Willow Bunch",
    		"Windthorst",
    		"Wiseton",
    		"Wolseley",
    		"Wood Mountain",
    		"Wynyard",
    		"Yarbo",
    		"Yellow Grass",
    		"Yorkton",
    		"Young",
    		"Zealandia",
    		"Zelma",
    		"Zenon Park"};

    		String[] namesMN = new String[]{
    		"Altona",
    		"Arborg",
    		"Beausejour",
    		"Brandon",
    		"Carberry",
    		"Carman",
    		"Churchill",
    		"Dauphin",
    		"Dunnottar",
    		"Flin Flon",
    		"Gillam",
    		"Grand Rapids",
    		"Lac du Bonnet",
    		"Leaf Rapids",
    		"Lynn Lake",
    		"Melita",
    		"Minnedosa",
    		"Morden",
    		"Morris",
    		"Neepawa",
    		"Niverville",
    		"The Pas",
    		"Portage la Prairie",
    		"Powerview-Pine Falls",
    		"Selkirk",
    		"Snow Lake",
    		"Ste. Anne",
    		"Steinbach",
    		"Stonewall",
    		"St-Pierre-Jolys",
    		"Swan River",
    		"Teulon",
    		"Thompson",
    		"Virden",
    		"Winkler",
    		"Winnipeg",
    		"Winnipeg Beach"};

    		String[] namesON = new String[]{
    		"Addington Highlands",
    		"Adelaide-Metcalfe",
    		"Adjala-Tosorontio",
    		"Admaston/Bromley",
    		"Ajax",
    		"Alberton",
    		"Alfred and Plantagenet",
    		"Algonquin Highlands",
    		"Alnwick/Haldimand",
    		"Amaranth",
    		"Amherstburg",
    		"The Archipelago",
    		"Armour",
    		"Armstrong",
    		"Arnprior",
    		"Arran-Elderslie",
    		"Ashfield-Colborne-Wawanosh",
    		"Asphodel-Norwood",
    		"Assiginack",
    		"Athens",
    		"Atikokan",
    		"Augusta",
    		"Aurora",
    		"Aylmer",
    		"Baldwin",
    		"Bancroft",
    		"Barrie",
    		"Bayham",
    		"Beckwith",
    		"Belleville",
    		"Billings",
    		"Black River-Matheson",
    		"Blandford-Blenheim",
    		"Blind River",
    		"The Blue Mountains",
    		"Bluewater",
    		"Bonfield",
    		"Bonnechere Valley",
    		"Bracebridge",
    		"Bradford West Gwillimbury",
    		"Brampton",
    		"Brant",
    		"Brantford",
    		"Brethour",
    		"Brighton",
    		"Brock",
    		"Brockton",
    		"Brockville",
    		"Brooke-Alvinston",
    		"Bruce Mines",
    		"Brudenell, Lyndoch and Raglan",
    		"Burk's Falls",
    		"Burlington",
    		"Burpee and Mills",
    		"Caledon",
    		"Callander",
    		"Calvin",
    		"Cambridge",
    		"Carleton Place",
    		"Carling",
    		"Carlow/Mayo",
    		"Casey",
    		"Casselman",
    		"Cavan-Monaghan",
    		"Central Elgin",
    		"Central Frontenac",
    		"Central Huron",
    		"Central Manitoulin",
    		"Centre Hastings",
    		"Centre Wellington",
    		"Chamberlain",
    		"Champlain",
    		"Chapleau",
    		"Chapple",
    		"Charlton and Dack",
    		"Chatham-Kent",
    		"Chatsworth",
    		"Chisholm",
    		"Clarence-Rockland",
    		"Clarington",
    		"Clearview",
    		"Cobalt",
    		"Cobourg",
    		"Cochrane",
    		"Cockburn Island",
    		"Coleman",
    		"Collingwood",
    		"Conmee",
    		"Cornwall",
    		"Cramahe",
    		"Dawn-Euphemia",
    		"Dawson",
    		"Deep River",
    		"Deseronto",
    		"Dorion",
    		"Douro-Dummer",
    		"Drummond/North Elmsley",
    		"Dryden",
    		"Dubreuilville",
    		"Dutton/Dunwich",
    		"Dysart, Dudley, Harcourt,",
    		"Guilford, Harburn, Bruton,",
    		"Havelock, Eyre and Clyde",
    		"Ear Falls",
    		"East Ferris",
    		"East Garafraxa",
    		"East Gwillimbury",
    		"East Hawkesbury",
    		"East Zorra-Tavistock",
    		"Edwardsburgh/Cardinal",
    		"Elizabethtown-Kitley",
    		"Elliot Lake",
    		"Emo",
    		"Englehart",
    		"Enniskillen",
    		"Erin",
    		"Espanola",
    		"Essa",
    		"Essex",
    		"Evanturel",
    		"Faraday",
    		"Fauquier-Strickland",
    		"Fort Erie",
    		"Fort Frances",
    		"French River",
    		"Front of Yonge",
    		"Frontenac Islands",
    		"Gananoque",
    		"Gauthier",
    		"Georgian Bay",
    		"Georgian Bluffs",
    		"Georgina",
    		"Gillies",
    		"Goderich",
    		"Gordon/Barrie Island",
    		"Gore Bay",
    		"Grand Valley",
    		"Gravenhurst",
    		"Greater Madawaska",
    		"Greater Napanee",
    		"Greater Sudbury",
    		"Greenstone",
    		"Grey Highlands",
    		"Grimsby",
    		"Guelph/Eramosa",
    		"Guelph",
    		"Haldimand",
    		"Halton Hills",
    		"Hamilton",
    		"Hamilton",
    		"Hanover",
    		"Harley",
    		"Harris",
    		"Hastings Highlands",
    		"Havelock-Belmont-Methuen",
    		"Hawkesbury",
    		"Head, Clara and Maria",
    		"Hearst",
    		"Highlands East",
    		"Hilliard",
    		"Hilton",
    		"Hilton Beach",
    		"Hornepayne",
    		"Horton",
    		"Howick",
    		"Hudson",
    		"Huntsville",
    		"Huron East",
    		"Huron Shores",
    		"Huron-Kinloss",
    		"Ignace",
    		"Ingersoll",
    		"Innisfil",
    		"Iroquois Falls",
    		"James",
    		"Jocelyn",
    		"Johnson",
    		"Joly",
    		"Kapuskasing",
    		"Kawartha Lakes",
    		"Kearney",
    		"Kenora",
    		"Kerns",
    		"Killaloe, Hagarty and Richards",
    		"Killarney",
    		"Kincardine",
    		"King",
    		"Kingston",
    		"Kingsville",
    		"Kirkland Lake",
    		"Kitchener",
    		"La Vallee",
    		"Laird",
    		"Lake of Bays",
    		"Lake of the Woods",
    		"Lakeshore",
    		"Lambton Shores",
    		"Lanark Highlands",
    		"Larder Lake",
    		"LaSalle",
    		"Latchford",
    		"Laurentian Hills",
    		"Laurentian Valley",
    		"Leamington",
    		"Leeds and the Thousand Islands",
    		"Limerick",
    		"Lincoln",
    		"London",
    		"Loyalist",
    		"Lucan Biddulph",
    		"Macdonald, Meredith and",
    		"Aberdeen Additional",
    		"Machar",
    		"Machin",
    		"Madawaska Valley",
    		"Madoc",
    		"Magnetawan",
    		"Malahide",
    		"Manitouwadge",
    		"Mapleton",
    		"Marathon",
    		"Markham",
    		"Markstay-Warren",
    		"Marmora and Lake",
    		"Matachewan",
    		"Mattawa",
    		"Mattawan",
    		"Mattice-Val Côté",
    		"McDougall",
    		"McGarry",
    		"McKellar",
    		"McMurrich/Monteith",
    		"McNab/Braeside",
    		"Meaford",
    		"Melancthon",
    		"Merrickville-Wolford",
    		"Middlesex Centre",
    		"Midland",
    		"Milton",
    		"Minden Hills",
    		"Minto",
    		"Mississauga",
    		"Mississippi Mills",
    		"Mono",
    		"Montague",
    		"Moonbeam",
    		"Moosonee",
    		"Morley",
    		"Morris-Turnberry",
    		"Mulmur",
    		"Muskoka Lakes",
    		"Nairn and Hyman",
    		"The Nation",
    		"Neebing",
    		"New Tecumseth",
    		"Newbury",
    		"Newmarket",
    		"Niagara Falls",
    		"Niagara-on-the-Lake",
    		"Nipigon",
    		"Nipissing",
    		"Norfolk",
    		"North Algona Wilberforce",
    		"North Bay",
    		"North Dumfries",
    		"North Dundas",
    		"North Frontenac",
    		"North Glengarry",
    		"North Grenville",
    		"North Huron",
    		"North Kawartha",
    		"North Middlesex",
    		"North Perth",
    		"The North Shore",
    		"North Stormont",
    		"Northeastern Manitoulinand the Islands",
    		"Northern Bruce Peninsula",
    		"Norwich",
    		"Oakville",
    		"O'Connor",
    		"Oil Springs",
    		"Oliver Paipoonge",
    		"Opasatika",
    		"Orangeville",
    		"Orillia",
    		"Oro-Medonte",
    		"Oshawa",
    		"Otonabee-South Monaghan",
    		"Ottawa",
    		"Owen Sound",
    		"Papineau-Cameron",
    		"Parry Sound",
    		"Pelee",
    		"Pelham",
    		"Pembroke",
    		"Penetanguishene",
    		"Perry",
    		"Perth",
    		"Perth East",
    		"Perth South",
    		"Petawawa",
    		"Peterborough",
    		"Petrolia",
    		"Pickering",
    		"Pickle Lake",
    		"Plummer Additional",
    		"Plympton-Wyoming",
    		"Point Edward",
    		"Port Colborne",
    		"Port Hope",
    		"Powassan",
    		"Prescott",
    		"Prince",
    		"Prince Edward",
    		"Puslinch",
    		"Quinte West",
    		"Rainy River",
    		"Ramara",
    		"Red Lake",
    		"Red Rock",
    		"Renfrew",
    		"Richmond Hill",
    		"Rideau Lakes",
    		"Russell",
    		"Ryerson",
    		"Sables-Spanish Rivers",
    		"Sarnia",
    		"Saugeen Shores",
    		"Sault Ste. Marie",
    		"Schreiber",
    		"Scugog",
    		"Seguin",
    		"Selwyn",
    		"Severn",
    		"Shelburne",
    		"Shuniah",
    		"Sioux Lookout",
    		"Sioux Narrows-Nestor Falls",
    		"Smiths Falls",
    		"Smooth Rock Falls",
    		"South Algonquin",
    		"South Bruce Peninsula",
    		"South Bruce",
    		"South Dundas",
    		"South Frontenac",
    		"South Glengarry",
    		"South Huron",
    		"South River",
    		"South Stormont",
    		"Southgate",
    		"Southwest Middlesex",
    		"South-West Oxford",
    		"Southwold",
    		"Spanish",
    		"Springwater",
    		"St. Catharines",
    		"St. Charles",
    		"St. Clair",
    		"St. Joseph",
    		"St. Marys",
    		"St. Thomas",
    		"Stirling-Rawdon",
    		"Stone Mills",
    		"Stratford",
    		"Strathroy-Caradoc",
    		"Strong",
    		"Sundridge",
    		"Tarbutt",
    		"Tay",
    		"Tay Valley",
    		"Tecumseh",
    		"Tehkummah",
    		"Temagami",
    		"Temiskaming Shores",
    		"Terrace Bay",
    		"Thames Centre",
    		"Thessalon",
    		"Thornloe",
    		"Thorold",
    		"Thunder Bay",
    		"Tillsonburg",
    		"Timmins",
    		"Tiny",
    		"Toronto",
    		"Trent Hills",
    		"Trent Lakes",
    		"Tudor and Cashel",
    		"Tweed",
    		"Tyendinaga",
    		"Uxbridge",
    		"Val Rita-Harty",
    		"Vaughan",
    		"Wainfleet",
    		"Warwick",
    		"Wasaga Beach",
    		"Waterloo",
    		"Wawa",
    		"Welland",
    		"Wellesley",
    		"Wellington North",
    		"West Elgin",
    		"West Grey",
    		"West Lincoln",
    		"West Nipissing",
    		"West Perth",
    		"Westport",
    		"Whitby",
    		"Whitchurch-Stouffville",
    		"White River",
    		"Whitestone",
    		"Whitewater Region",
    		"Wilmot",
    		"Windsor",
    		"Wollaston",
    		"Woodstock",
    		"Woolwich",
    		"Zorra"};


    		String[] namesQU = new String[]{
    		"Abercorn",
    		"Acton Vale",
    		"Adstock",
    		"Aguanish",
    		"Albanel",
    		"Albertville",
    		"Alleyn-et-Cawood",
    		"Alma",
    		"Amherst",
    		"Amos",
    		"Amqui",
    		"Ange-Gardien",
    		"Angliers",
    		"Armagh",
    		"Arundel",
    		"Asbestos",
    		"Ascot Corner",
    		"Aston-Jonction",
    		"Auclair",
    		"Audet",
    		"Aumond",
    		"Austin",
    		"Authier",
    		"Authier-Nord",
    		"Ayer's Cliff",
    		"Baie-Comeau",
    		"Baie-des-Sables",
    		"Baie-du-Febvre",
    		"Baie-D'Urfé",
    		"Baie-Johan-Beetz",
    		"Baie-Sainte-Catherine",
    		"Baie-Saint-Paul",
    		"Baie-Trinité",
    		"Barkmere",
    		"Barnston-Ouest",
    		"Barraute",
    		"Batiscan",
    		"Beaconsfield",
    		"Béarn",
    		"Beauceville",
    		"Beauharnois",
    		"Beaulac-Garthby",
    		"Beaumont",
    		"Beaupré",
    		"Bécancour",
    		"Bedford",
    		"Bedford",
    		"Bégin",
    		"Belcourt",
    		"Belleterre",
    		"Beloeil",
    		"Berry",
    		"Berthier-sur-Mer",
    		"Berthierville",
    		"Béthanie",
    		"Biencourt",
    		"Blainville",
    		"Blanc-Sablon",
    		"Blue Sea",
    		"Boileau",
    		"Boisbriand",
    		"Boischatel",
    		"Bois-des-Filion",
    		"Bois-Franc",
    		"Bolton-Est",
    		"Bolton-Ouest",
    		"Bonaventure",
    		"Bonne-Espérance",
    		"Bonsecours",
    		"Boucherville",
    		"Bouchette",
    		"Bowman",
    		"Brébeuf",
    		"Brigham",
    		"Bristol",
    		"Brome",
    		"Bromont",
    		"Brossard",
    		"Brownsburg-Chatham",
    		"Bryson",
    		"Bury",
    		"Cacouna",
    		"Calixa-Lavallée",
    		"Campbell's Bay",
    		"Candiac",
    		"Cantley",
    		"Cap-Chat",
    		"Caplan",
    		"Cap-Saint-Ignace",
    		"Cap-Santé",
    		"Carignan",
    		"Carleton-sur-Mer",
    		"Cascapédia-Saint-Jules",
    		"Causapscal",
    		"Cayamant",
    		"Chambly",
    		"Chambord",
    		"Champlain",
    		"Champneuf",
    		"Chandler",
    		"Chapais",
    		"Charette",
    		"Charlemagne",
    		"Chartierville",
    		"Châteauguay",
    		"Château-Richer",
    		"Chazel",
    		"Chelsea",
    		"Chénéville",
    		"Chertsey",
    		"Chesterville",
    		"Chibougamau",
    		"Chichester",
    		"Chute-aux-Outardes",
    		"Chute-Saint-Philippe",
    		"Clarendon",
    		"Clermont",
    		"Clermont",
    		"Clerval",
    		"Cleveland",
    		"Cloridorme",
    		"Coaticook",
    		"Colombier",
    		"Compton",
    		"Contrecoeur",
    		"Cookshire-Eaton",
    		"Côte Saint-Luc",
    		"Coteau-du-Lac",
    		"Côte-Nord-du-Golfe-du-Saint-Laurent",
    		"Courcelles",
    		"Cowansville",
    		"Crabtree",
    		"Danville",
    		"Daveluyville",
    		"Dégelis",
    		"Déléage",
    		"Delson",
    		"Denholm",
    		"Desbiens",
    		"Deschaillons-sur-Saint-Laurent",
    		"Deschambault-Grondines",
    		"Deux-Montagnes",
    		"Disraeli",
    		"Disraeli",
    		"Dixville",
    		"Dolbeau-Mistassini",
    		"Dollard-des-Ormeaux",
    		"Donnacona",
    		"Dorval",
    		"Dosquet",
    		"Drummondville",
    		"Dudswell",
    		"Duhamel",
    		"Duhamel-Ouest",
    		"Dundee",
    		"Dunham",
    		"Duparquet",
    		"Dupuy",
    		"Durham-Sud",
    		"East Angus",
    		"East Broughton",
    		"East Farnham",
    		"East Hereford",
    		"Eastman",
    		"Egan-Sud",
    		"Elgin",
    		"Entrelacs",
    		"Escuminac",
    		"Esprit-Saint",
    		"Estérel",
    		"Farnham",
    		"Fassett",
    		"Ferland-et-Boilleau",
    		"Ferme-Neuve",
    		"Fermont",
    		"Forestville",
    		"Fort-Coulonge",
    		"Fortierville",
    		"Fossambault-sur-le-Lac",
    		"Frampton",
    		"Franklin",
    		"Franquelin",
    		"Frelighsburg",
    		"Frontenac",
    		"Fugèreville",
    		"Gallichan",
    		"Gaspé",
    		"Gatineau",
    		"Girardville",
    		"Godbout",
    		"Godmanchester",
    		"Gore",
    		"Gracefield",
    		"Granby",
    		"Grand-Métis",
    		"Grand-Remous",
    		"Grand-Saint-Esprit",
    		"Grande-Rivière",
    		"Grande-Vallée",
    		"Grandes-Piles",
    		"Grenville",
    		"Grenville-sur-la-Rouge",
    		"Gros-Mécatina",
    		"Grosse-Île",
    		"Grosses-Roches",
    		"Guérin",
    		"Ham-Nord",
    		"Ham-Sud",
    		"Hampden",
    		"Hampstead",
    		"Harrington",
    		"Hatley",
    		"Hatley",
    		"Havelock",
    		"Havre-Saint-Pierre",
    		"Hébertville",
    		"Hébertville-Station",
    		"Hemmingford",
    		"Hemmingford",
    		"Henryville",
    		"Hérouxville",
    		"Hinchinbrooke",
    		"Honfleur",
    		"Hope",
    		"Hope Town",
    		"Howick",
    		"Huberdeau",
    		"Hudson",
    		"Huntingdon",
    		"Inverness",
    		"Irlande",
    		"Ivry-sur-le-Lac",
    		"Joliette",
    		"Kamouraska",
    		"Kazabazua",
    		"Kiamika",
    		"Kingsbury",
    		"Kingsey Falls",
    		"Kinnear's Mills",
    		"Kipawa",
    		"Kirkland",
    		"La Bostonnais",
    		"La Conception",
    		"La Corne",
    		"La Doré",
    		"La Durantaye",
    		"La Guadeloupe",
    		"La Macaza",
    		"La Malbaie",
    		"La Martre",
    		"La Minerve",
    		"La Morandière",
    		"La Motte",
    		"La Patrie",
    		"La Pêche",
    		"La Pocatière",
    		"La Prairie",
    		"La Présentation",
    		"La Rédemption",
    		"La Reine",
    		"La Sarre",
    		"La Trinité-des-Monts",
    		"La Tuque",
    		"La Visitation-de-l'Île-Dupas",
    		"La Visitation-de-Yamaska",
    		"Labelle",
    		"Labrecque",
    		"Lac-au-Saumon",
    		"Lac-aux-Sables",
    		"Lac-Beauport",
    		"Lac-Bouchette",
    		"Lac-Brome",
    		"Lac-Delage",
    		"Lac-des-Aigles",
    		"Lac-des-Écorces",
    		"Lac-des-Plages",
    		"Lac-des-Seize-Îles",
    		"Lac-Drolet",
    		"Lac-du-Cerf",
    		"Lac-Édouard",
    		"Lac-Etchemin",
    		"Lac-Frontière",
    		"Lac-Mégantic",
    		"Lac-Poulin",
    		"Lac-Saguay",
    		"Lac-Saint-Joseph",
    		"Lac-Saint-Paul",
    		"Lac-Sainte-Marie",
    		"Lac-Sergent",
    		"Lac-Simon",
    		"Lac-Supérieur",
    		"Lac-Tremblant-Nord",
    		"Lachute",
    		"Lacolle",
    		"Laforce",
    		"Lamarche",
    		"Lambton",
    		"L'Ancienne-Lorette",
    		"Landrienne",
    		"L'Ange-Gardien",
    		"L'Ange-Gardien",
    		"Lanoraie",
    		"L'Anse-Saint-Jean",
    		"Lantier",
    		"Larouche",
    		"L'Ascension",
    		"L'Ascension-de-Notre-Seigneur",
    		"L'Ascension-de-Patapédia",
    		"L'Assomption",
    		"Latulipe-et-Gaboury",
    		"Launay",
    		"Laurier-Station",
    		"Laurierville",
    		"Laval",
    		"Lavaltrie",
    		"L'Avenir",
    		"Laverlochère",
    		"Lawrenceville",
    		"Lebel-sur-Quévillon",
    		"Leclercville",
    		"Lefebvre",
    		"Lejeune",
    		"Lemieux",
    		"L'Épiphanie",
    		"L'Épiphanie",
    		"Léry",
    		"Les Bergeronnes",
    		"Les Cèdres",
    		"Les Coteaux",
    		"Les Éboulements",
    		"Les Escoumins",
    		"Les Hauteurs",
    		"Les Îles-de-la-Madeleine",
    		"Les Méchins",
    		"Lévis",
    		"L'Île-Cadieux",
    		"L'Île-d'Anticosti",
    		"L'Île-Dorval",
    		"L'Île-du-Grand-Calumet",
    		"L'Île-Perrot",
    		"Lingwick",
    		"L'Isle-aux-Allumettes",
    		"L'Isle-aux-Coudres",
    		"L'Isle-Verte",
    		"L'Islet",
    		"Litchfield",
    		"Lochaber",
    		"Lochaber-Partie-Ouest",
    		"Longue-Pointe-de-Mingan",
    		"Longue-Rive",
    		"Longueuil",
    		"Lorraine",
    		"Lorrainville",
    		"Lotbinière",
    		"Louiseville",
    		"Low",
    		"Lyster",
    		"Macamic",
    		"Maddington Falls",
    		"Magog",
    		"Malartic",
    		"Mandeville",
    		"Maniwaki",
    		"Manseau",
    		"Mansfield-et-Pontefract",
    		"Maria",
    		"Maricourt",
    		"Marieville",
    		"Marsoui",
    		"Marston",
    		"Martinville",
    		"Mascouche",
    		"Maskinongé",
    		"Massueville",
    		"Matagami",
    		"Matane",
    		"Matapédia",
    		"Mayo",
    		"McMasterville",
    		"Melbourne",
    		"Mercier",
    		"Messines",
    		"Métabetchouan-Lac-à-la-Croix",
    		"Métis-sur-Mer",
    		"Milan",
    		"Mille-Isles",
    		"Mirabel",
    		"Moffet",
    		"Mont-Carmel",
    		"Mont-Joli",
    		"Mont-Laurier",
    		"Mont-Royal",
    		"Mont-Saint-Grégoire",
    		"Mont-Saint-Hilaire",
    		"Mont-Saint-Michel",
    		"Mont-Saint-Pierre",
    		"Mont-Tremblant",
    		"Montcalm",
    		"Montcerf-Lytton",
    		"Montebello",
    		"Montmagny",
    		"Montpellier",
    		"Montreal",
    		"Montréal-Est",
    		"Montreal-Ouest",
    		"Morin-Heights",
    		"Mulgrave-et-Derry",
    		"Murdochville",
    		"Namur",
    		"Nantes",
    		"Napierville",
    		"Natashquan",
    		"Nédélec",
    		"Neuville",
    		"New Carlisle",
    		"New Richmond",
    		"Newport",
    		"Nicolet",
    		"Nominingue",
    		"Normandin",
    		"Normétal",
    		"North Hatley",
    		"Notre-Dame-Auxiliatrice-de-Buckland",
    		"Notre-Dame-de-Bonsecours",
    		"Notre-Dame-de-Ham",
    		"Notre-Dame-de-la-Merci",
    		"Notre-Dame-de-la-Paix",
    		"Notre-Dame-de-la-Salette",
    		"Notre-Dame-de-l'Île-Perrot",
    		"Notre-Dame-de-Lorette",
    		"Notre-Dame-de-Lourdes",
    		"Notre-Dame-de-Lourdes",
    		"Notre-Dame-de-Montauban",
    		"Notre-Dame-de-Pontmain",
    		"Notre-Dame-de-Stanbridge",
    		"Notre-Dame-des-Anges",
    		"Notre-Dame-des-Bois",
    		"Notre-Dame-des-Monts",
    		"Notre-Dame-des-Neiges",
    		"Notre-Dame-des-Pins",
    		"Notre-Dame-des-Prairies",
    		"Notre-Dame-des-Sept-Douleurs",
    		"Notre-Dame-du-Bon-Conseil",
    		"Notre-Dame-du-Bon-Conseil",
    		"Notre-Dame-du-Laus",
    		"Notre-Dame-du-Mont-Carmel",
    		"Notre-Dame-du-Nord",
    		"Notre-Dame-du-Portage",
    		"Notre-Dame-du-Rosaire",
    		"Notre-Dame-du-Sacré-Coeur-d'Issoudun",
    		"Nouvelle",
    		"Noyan",
    		"Ogden",
    		"Oka",
    		"Orford",
    		"Ormstown",
    		"Otter Lake",
    		"Otterburn Park",
    		"Packington",
    		"Padoue",
    		"Palmarolle",
    		"Papineauville",
    		"Parisville",
    		"Paspébiac",
    		"Percé",
    		"Péribonka",
    		"Petit-Saguenay",
    		"Petite-Rivière-Saint-François",
    		"Petite-Vallée",
    		"Piedmont",
    		"Pierreville",
    		"Pike River",
    		"Pincourt",
    		"Piopolis",
    		"Plaisance",
    		"Plessisville",
    		"Plessisville",
    		"Pohénégamook",
    		"Pointe-à-la-Croix",
    		"Pointe-aux-Outardes",
    		"Pointe-Calumet",
    		"Pointe-Claire",
    		"Pointe-des-Cascades",
    		"Pointe-Fortune",
    		"Pointe-Lebel",
    		"Pontiac",
    		"Pont-Rouge",
    		"Port-Cartier",
    		"Port-Daniel-Gascons",
    		"Portage-du-Fort",
    		"Portneuf",
    		"Portneuf-sur-Mer",
    		"Potton",
    		"Poularies",
    		"Preissac",
    		"Prévost",
    		"Price",
    		"Princeville",
    		"Quebec City",
    		"Racine",
    		"Ragueneau",
    		"Rapide-Danseur",
    		"Rapides-des-Joachims",
    		"Rawdon",
    		"Rémigny",
    		"Repentigny",
    		"Richelieu",
    		"Richmond",
    		"Rigaud",
    		"Rimouski",
    		"Ripon",
    		"Ristigouche-Partie-Sud-Est",
    		"Rivière-à-Claude",
    		"Rivière-à-Pierre",
    		"Rivière-au-Tonnerre",
    		"Rivière-Beaudette",
    		"Rivière-Bleue",
    		"Rivière-du-Loup",
    		"Rivière-Éternité",
    		"Rivière-Héva",
    		"Rivière-Ouelle",
    		"Rivière-Rouge",
    		"Rivière-Saint-Jean",
    		"Roberval",
    		"Rochebaucourt",
    		"Roquemaure",
    		"Rosemère",
    		"Rougemont",
    		"Rouyn-Noranda",
    		"Roxton",
    		"Roxton Falls",
    		"Roxton Pond",
    		"Sacré-Coeur",
    		"Sacré-Coeur-de-Jésus",
    		"Saguenay",
    		"Saint-Adalbert",
    		"Saint-Adelme",
    		"Saint-Adelphe",
    		"Saint-Adolphe-d'Howard",
    		"Saint-Adrien",
    		"Saint-Adrien-d'Irlande",
    		"Saint-Agapit",
    		"Saint-Aimé",
    		"Saint-Aimé-des-Lacs",
    		"Saint-Aimé-du-Lac-des-Îles",
    		"Saint-Alban",
    		"Saint-Albert",
    		"Saint-Alexandre",
    		"Saint-Alexandre-de-Kamouraska",
    		"Saint-Alexandre-des-Lacs",
    		"Saint-Alexis",
    		"Saint-Alexis-de-Matapédia",
    		"Saint-Alexis-des-Monts",
    		"Saint-Alfred",
    		"Saint-Alphonse",
    		"Saint-Alphonse-de-Granby",
    		"Saint-Alphonse-Rodriguez",
    		"Saint-Amable",
    		"Saint-Ambroise",
    		"Saint-Ambroise-de-Kildare",
    		"Saint-Anaclet-de-Lessard",
    		"Saint-André",
    		"Saint-André-Avellin",
    		"Saint-André-d'Argenteuil",
    		"Saint-André-de-Restigouche",
    		"Saint-André-du-Lac-Saint-Jean",
    		"Saint-Anicet",
    		"Saint-Anselme",
    		"Saint-Antoine-de-l'Isle-aux-Grues",
    		"Saint-Antoine-de-Tilly",
    		"Saint-Antoine-sur-Richelieu",
    		"Saint-Antonin",
    		"Saint-Apollinaire",
    		"Saint-Armand",
    		"Saint-Arsène",
    		"Saint-Athanase",
    		"Saint-Aubert",
    		"Saint-Augustin",
    		"Saint-Augustin",
    		"Saint-Augustin-de-Desmaures",
    		"Saint-Augustin-de-Woburn",
    		"Saint-Barnabé",
    		"Saint-Barnabé-Sud",
    		"Saint-Barthélemy",
    		"Saint-Basile",
    		"Saint-Basile-le-Grand",
    		"Saint-Benjamin",
    		"Saint-Benoît-du-Lac",
    		"Saint-Benoît-Labre",
    		"Saint-Bernard",
    		"Saint-Bernard-de-Lacolle",
    		"Saint-Bernard-de-Michaudville",
    		"Saint-Blaise-sur-Richelieu",
    		"Saint-Bonaventure",
    		"Saint-Boniface",
    		"Saint-Bruno",
    		"Saint-Bruno-de-Guigues",
    		"Saint-Bruno-de-Kamouraska",
    		"Saint-Bruno-de-Montarville",
    		"Saint-Calixte",
    		"Saint-Camille",
    		"Saint-Camille-de-Lellis",
    		"Saint-Casimir",
    		"Saint-Célestin",
    		"Saint-Célestin",
    		"Saint-Césaire",
    		"Saint-Charles-Borromée",
    		"Saint-Charles-de-Bellechasse",
    		"Saint-Charles-de-Bourget",
    		"Saint-Charles-Garnier",
    		"Saint-Charles-sur-Richelieu",
    		"Saint-Christophe-d'Arthabaska",
    		"Saint-Chrysostome",
    		"Saint-Claude",
    		"Saint-Clément",
    		"Saint-Cléophas",
    		"Saint-Cléophas-de-Brandon",
    		"Saint-Clet",
    		"Saint-Colomban",
    		"Saint-Côme",
    		"Saint-Côme-Linière",
    		"Saint-Constant",
    		"Saint-Cuthbert",
    		"Saint-Cyprien",
    		"Saint-Cyprien",
    		"Saint-Cyprien-de-Napierville",
    		"Saint-Cyrille-de-Lessard",
    		"Saint-Cyrille-de-Wendover",
    		"Saint-Damase",
    		"Saint-Damase",
    		"Saint-Damase-de-L'Islet",
    		"Saint-Damien",
    		"Saint-Damien-de-Buckland",
    		"Saint-David",
    		"Saint-David-de-Falardeau",
    		"Saint-Denis-De La Bouteillerie",
    		"Saint-Denis-de-Brompton",
    		"Saint-Denis-sur-Richelieu",
    		"Saint-Didace",
    		"Saint-Dominique",
    		"Saint-Dominique-du-Rosaire",
    		"Saint-Donat",
    		"Saint-Donat",
    		"Saint-Edmond-de-Grantham",
    		"Saint-Edmond-les-Plaines",
    		"Saint-Édouard",
    		"Saint-Édouard-de-Fabre",
    		"Saint-Édouard-de-Lotbinière",
    		"Saint-Édouard-de-Maskinongé",
    		"Saint-Élie-de-Caxton",
    		"Saint-Éloi",
    		"Saint-Elphège",
    		"Saint-Elzéar",
    		"Saint-Elzéar",
    		"Saint-Elzéar-de-Témiscouata",
    		"Saint-Émile-de-Suffolk",
    		"Saint-Éphrem-de-Beauce",
    		"Saint-Épiphane",
    		"Saint-Esprit",
    		"Saint-Étienne-de-Beauharnois",
    		"Saint-Étienne-de-Bolton",
    		"Saint-Étienne-des-Grès",
    		"Saint-Eugène",
    		"Saint-Eugène-d'Argentenay",
    		"Saint-Eugène-de-Guigues",
    		"Saint-Eugène-de-Ladrière",
    		"Saint-Eusèbe",
    		"Saint-Eustache",
    		"Saint-Évariste-de-Forsyth",
    		"Saint-Fabien",
    		"Saint-Fabien-de-Panet",
    		"Saint-Faustin-Lac-Carré",
    		"Saint-Félicien",
    		"Saint-Félix-de-Dalquier",
    		"Saint-Félix-de-Kingsey",
    		"Saint-Félix-de-Valois",
    		"Saint-Félix-d'Otis",
    		"Saint-Ferdinand",
    		"Saint-Ferréol-les-Neiges",
    		"Saint-Flavien",
    		"Saint-Fortunat",
    		"Saint-François-d'Assise",
    		"Saint-François-de-la-Rivière-du-Sud",
    		"Saint-François-de-l'Île-d'Orléans",
    		"Saint-François-de-Sales",
    		"Saint-François-du-Lac",
    		"Saint-François-Xavier-de-Brompton",
    		"Saint-François-Xavier-de-Viger",
    		"Saint-Frédéric",
    		"Saint-Fulgence",
    		"Saint-Gabriel",
    		"Saint-Gabriel-de-Brandon",
    		"Saint-Gabriel-de-Rimouski",
    		"Saint-Gabriel-de-Valcartier",
    		"Saint-Gabriel-Lalemant",
    		"Saint-Gédéon",
    		"Saint-Gédéon-de-Beauce",
    		"Saint-Georges",
    		"Saint-Georges-de-Clarenceville",
    		"Saint-Georges-de-Windsor",
    		"Saint-Gérard-Majella",
    		"Saint-Germain",
    		"Saint-Germain-de-Grantham",
    		"Saint-Gervais",
    		"Saint-Gilbert",
    		"Saint-Gilles",
    		"Saint-Godefroi",
    		"Saint-Guillaume",
    		"Saint-Guy",
    		"Saint-Henri",
    		"Saint-Henri-de-Taillon",
    		"Saint-Herménégilde",
    		"Saint-Hilaire-de-Dorset",
    		"Saint-Hilarion",
    		"Saint-Hippolyte",
    		"Saint-Honoré",
    		"Saint-Honoré-de-Shenley",
    		"Saint-Honoré-de-Témiscouata",
    		"Saint-Hubert-de-Rivière-du-Loup",
    		"Saint-Hugues",
    		"Saint-Hyacinthe",
    		"Saint-Ignace-de-Loyola",
    		"Saint-Ignace-de-Stanbridge",
    		"Saint-Irénée",
    		"Saint-Isidore",
    		"Saint-Isidore",
    		"Saint-Isidore-de-Clifton",
    		"Saint-Jacques",
    		"Saint-Jacques-de-Leeds",
    		"Saint-Jacques-le-Majeur-de-Wolfestown",
    		"Saint-Jacques-le-Mineur",
    		"Saint-Janvier-de-Joly",
    		"Saint-Jean-Baptiste",
    		"Saint-Jean-de-Brébeuf",
    		"Saint-Jean-de-Cherbourg",
    		"Saint-Jean-de-Dieu",
    		"Saint-Jean-de-la-Lande",
    		"Saint-Jean-de-l'Île-d'Orléans",
    		"Saint-Jean-de-Matha",
    		"Saint-Jean-Port-Joli",
    		"Saint-Jean-sur-Richelieu",
    		"Saint-Jérôme",
    		"Saint-Joachim",
    		"Saint-Joachim-de-Shefford",
    		"Saint-Joseph-de-Beauce",
    		"Saint-Joseph-de-Coleraine",
    		"Saint-Joseph-de-Kamouraska",
    		"Saint-Joseph-de-Lepage",
    		"Saint-Joseph-des-Érables",
    		"Saint-Joseph-de-Sorel",
    		"Saint-Joseph-du-Lac",
    		"Saint-Jude",
    		"Saint-Jules",
    		"Saint-Julien",
    		"Saint-Just-de-Bretenières",
    		"Saint-Juste-du-Lac",
    		"Saint-Justin",
    		"Saint-Lambert",
    		"Saint-Lambert",
    		"Saint-Lambert-de-Lauzon",
    		"Saint-Laurent-de-l'Île-d'Orléans",
    		"Saint-Lazare",
    		"Saint-Lazare-de-Bellechasse",
    		"Saint-Léandre",
    		"Saint-Léonard-d'Aston",
    		"Saint-Léonard-de-Portneuf",
    		"Saint-Léon-de-Standon",
    		"Saint-Léon-le-Grand",
    		"Saint-Léon-le-Grand",
    		"Saint-Liboire",
    		"Saint-Liguori",
    		"Saint-Lin-Laurentides",
    		"Saint-Louis",
    		"Saint-Louis-de-Blandford",
    		"Saint-Louis-de-Gonzague",
    		"Saint-Louis-de-Gonzague",
    		"Saint-Louis-de-Gonzague-du-Cap-Tourmente",
    		"Saint-Louis-du-Ha! Ha!",
    		"Saint-Luc-de-Bellechasse",
    		"Saint-Luc-de-Vincennes",
    		"Saint-Lucien",
    		"Saint-Ludger",
    		"Saint-Ludger-de-Milot",
    		"Saint-Magloire",
    		"Saint-Majorique-de-Grantham",
    		"Saint-Malachie",
    		"Saint-Malo",
    		"Saint-Marc-de-Figuery",
    		"Saint-Marc-des-Carrières",
    		"Saint-Marc-du-Lac-Long",
    		"Saint-Marcel",
    		"Saint-Marcel-de-Richelieu",
    		"Saint-Marcellin",
    		"Saint-Marc-sur-Richelieu",
    		"Saint-Martin",
    		"Saint-Mathias-sur-Richelieu",
    		"Saint-Mathieu",
    		"Saint-Mathieu-de-Beloeil",
    		"Saint-Mathieu-de-Rioux",
    		"Saint-Mathieu-d'Harricana",
    		"Saint-Mathieu-du-Parc",
    		"Saint-Maurice",
    		"Saint-Maxime-du-Mont-Louis",
    		"Saint-Médard",
    		"Saint-Michel",
    		"Saint-Michel-de-Bellechasse",
    		"Saint-Michel-des-Saints",
    		"Saint-Michel-du-Squatec",
    		"Saint-Modeste",
    		"Saint-Moïse",
    		"Saint-Narcisse",
    		"Saint-Narcisse-de-Beaurivage",
    		"Saint-Narcisse-de-Rimouski",
    		"Saint-Nazaire",
    		"Saint-Nazaire-d'Acton",
    		"Saint-Nazaire-de-Dorchester",
    		"Saint-Nérée-de-Bellechasse",
    		"Saint-Noël",
    		"Saint-Norbert",
    		"Saint-Norbert-d'Arthabaska",
    		"Saint-Octave-de-Métis",
    		"Saint-Odilon-de-Cranbourne",
    		"Saint-Omer",
    		"Saint-Onésime-d'Ixworth",
    		"Saint-Ours",
    		"Saint-Pacôme",
    		"Saint-Pamphile",
    		"Saint-Pascal",
    		"Saint-Patrice-de-Beaurivage",
    		"Saint-Patrice-de-Sherrington",
    		"Saint-Paul",
    		"Saint-Paul-d'Abbotsford",
    		"Saint-Paul-de-la-Croix",
    		"Saint-Paul-de-l'Île-aux-Noix",
    		"Saint-Paul-de-Montminy",
    		"Saint-Paulin",
    		"Saint-Philémon",
    		"Saint-Philibert",
    		"Saint-Philippe",
    		"Saint-Philippe-de-Néri",
    		"Saint-Pie",
    		"Saint-Pie-de-Guire",
    		"Saint-Pierre",
    		"Saint-Pierre-Baptiste",
    		"Saint-Pierre-de-Broughton",
    		"Saint-Pierre-de-Lamy",
    		"Saint-Pierre-de-la-Rivière-du-Sud",
    		"Saint-Pierre-de-l'Île-d'Orléans",
    		"Saint-Pierre-les-Becquets",
    		"Saint-Placide",
    		"Saint-Polycarpe",
    		"Saint-Prime",
    		"Saint-Prosper",
    		"Saint-Prosper-de-Champlain",
    		"Saint-Raphaël",
    		"Saint-Raymond",
    		"Saint-Rémi",
    		"Saint-Rémi-de-Tingwick",
    		"Saint-René",
    		"Saint-René-de-Matane",
    		"Saint-Robert",
    		"Saint-Robert-Bellarmin",
    		"Saint-Roch-de-l'Achigan",
    		"Saint-Roch-de-Mékinac",
    		"Saint-Roch-de-Richelieu",
    		"Saint-Roch-des-Aulnaies",
    		"Saint-Roch-Ouest",
    		"Saint-Romain",
    		"Saint-Rosaire",
    		"Saint-Samuel",
    		"Saint-Sauveur",
    		"Saint-Sébastien",
    		"Saint-Sébastien",
    		"Saint-Sévère",
    		"Saint-Séverin",
    		"Saint-Séverin",
    		"Saint-Siméon",
    		"Saint-Siméon",
    		"Saint-Simon",
    		"Saint-Simon",
    		"Saint-Simon-les-Mines",
    		"Saint-Sixte",
    		"Saint-Stanislas",
    		"Saint-Stanislas",
    		"Saint-Stanislas-de-Kostka",
    		"Saint-Sulpice",
    		"Saint-Sylvère",
    		"Saint-Sylvestre",
    		"Saint-Télesphore",
    		"Saint-Tharcisius",
    		"Saint-Théodore-d'Acton",
    		"Saint-Théophile",
    		"Saint-Thomas",
    		"Saint-Thomas-Didyme",
    		"Saint-Thuribe",
    		"Saint-Tite",
    		"Saint-Tite-des-Caps",
    		"Saint-Ubalde",
    		"Saint-Ulric",
    		"Saint-Urbain",
    		"Saint-Urbain-Premier",
    		"Saint-Valentin",
    		"Saint-Valère",
    		"Saint-Valérien",
    		"Saint-Valérien-de-Milton",
    		"Saint-Vallier",
    		"Saint-Venant-de-Paquette",
    		"Saint-Vianney",
    		"Saint-Victor",
    		"Saint-Wenceslas",
    		"Saint-Zacharie",
    		"Saint-Zénon",
    		"Saint-Zénon-du-Lac-Humqui",
    		"Saint-Zéphirin-de-Courval",
    		"Saint-Zotique",
    		"Sainte-Adèle",
    		"Sainte-Agathe-de-Lotbinière",
    		"Sainte-Agathe-des-Monts",
    		"Sainte-Angèle-de-Mérici",
    		"Sainte-Angèle-de-Monnoir",
    		"Sainte-Angèle-de-Prémont",
    		"Sainte-Anne-de-Beaupré",
    		"Sainte-Anne-de-Bellevue",
    		"Sainte-Anne-de-la-Pérade",
    		"Sainte-Anne-de-la-Pocatière",
    		"Sainte-Anne-de-la-Rochelle",
    		"Sainte-Anne-de-Sabrevois",
    		"Sainte-Anne-des-Lacs",
    		"Sainte-Anne-des-Monts",
    		"Sainte-Anne-de-Sorel",
    		"Sainte-Anne-des-Plaines",
    		"Sainte-Anne-du-Lac",
    		"Sainte-Anne-du-Sault",
    		"Sainte-Apolline-de-Patton",
    		"Sainte-Aurélie",
    		"Sainte-Barbe",
    		"Sainte-Béatrix",
    		"Sainte-Brigide-d'Iberville",
    		"Sainte-Brigitte-de-Laval",
    		"Sainte-Brigitte-des-Saults",
    		"Sainte-Catherine",
    		"Sainte-Catherine-de-Hatley",
    		"Sainte-Catherine-de-la-Jacques-Cartier",
    		"Sainte-Cécile-de-Lévrard",
    		"Sainte-Cécile-de-Milton",
    		"Sainte-Cécile-de-Whitton",
    		"Sainte-Christine",
    		"Sainte-Christine-d'Auvergne",
    		"Sainte-Claire",
    		"Sainte-Clotilde",
    		"Sainte-Clotilde-de-Beauce",
    		"Sainte-Clotilde-de-Horton",
    		"Sainte-Croix",
    		"Sainte-Edwidge-de-Clifton",
    		"Sainte-Élisabeth",
    		"Sainte-Élizabeth-de-Warwick",
    		"Sainte-Émélie-de-l'Énergie",
    		"Sainte-Eulalie",
    		"Sainte-Euphémie-sur-Rivière-du-Sud",
    		"Sainte-Famille",
    		"Sainte-Félicité",
    		"Sainte-Félicité",
    		"Sainte-Flavie",
    		"Sainte-Florence",
    		"Sainte-Françoise",
    		"Sainte-Françoise",
    		"Sainte-Geneviève-de-Batiscan",
    		"Sainte-Geneviève-de-Berthier",
    		"Sainte-Germaine-Boulé",
    		"Sainte-Gertrude-Manneville",
    		"Sainte-Hedwidge",
    		"Sainte-Hélène-de-Bagot",
    		"Sainte-Hélène-de-Chester",
    		"Sainte-Hélène-de-Kamouraska",
    		"Sainte-Hélène-de-Mancebourg",
    		"Sainte-Hénédine",
    		"Sainte-Irène",
    		"Sainte-Jeanne-d'Arc",
    		"Sainte-Jeanne-d'Arc",
    		"Sainte-Julie",
    		"Sainte-Julienne",
    		"Sainte-Justine",
    		"Sainte-Justine-de-Newton",
    		"Sainte-Louise",
    		"Sainte-Luce",
    		"Sainte-Lucie-de-Beauregard",
    		"Sainte-Lucie-des-Laurentides",
    		"Sainte-Madeleine",
    		"Sainte-Madeleine-de-la-Rivière-Madeleine",
    		"Sainte-Marcelline-de-Kildare",
    		"Sainte-Marguerite",
    		"Sainte-Marguerite-du-Lac-Masson",
    		"Sainte-Marguerite-Marie",
    		"Sainte-Marie",
    		"Sainte-Marie-de-Blandford",
    		"Sainte-Marie-Madeleine",
    		"Sainte-Marie-Salomé",
    		"Sainte-Marthe",
    		"Sainte-Marthe-sur-le-Lac",
    		"Sainte-Martine",
    		"Sainte-Mélanie",
    		"Sainte-Monique",
    		"Sainte-Monique",
    		"Sainte-Paule",
    		"Sainte-Perpétue",
    		"Sainte-Perpétue",
    		"Sainte-Pétronille",
    		"Sainte-Praxède",
    		"Sainte-Rita",
    		"Sainte-Rose-de-Watford",
    		"Sainte-Rose-du-Nord",
    		"Sainte-Sabine",
    		"Sainte-Sabine",
    		"Sainte-Séraphine",
    		"Sainte-Sophie",
    		"Sainte-Sophie-de-Lévrard",
    		"Sainte-Sophie-d'Halifax",
    		"Sainte-Thècle",
    		"Sainte-Thérèse",
    		"Sainte-Thérèse-de-Gaspé",
    		"Sainte-Thérèse-de-la-Gatineau",
    		"Sainte-Ursule",
    		"Sainte-Victoire-de-Sorel",
    		"Saints-Anges",
    		"Saints-Martyrs-Canadiens",
    		"Salaberry-de-Valleyfield",
    		"Sayabec",
    		"Schefferville",
    		"Scotstown",
    		"Scott",
    		"Senneterre",
    		"Senneterre",
    		"Senneville",
    		"Sept-Îles",
    		"Shannon",
    		"Shawinigan",
    		"Shawville",
    		"Sheenboro",
    		"Shefford",
    		"Sherbrooke",
    		"Shigawake",
    		"Sorel-Tracy",
    		"Stanbridge East",
    		"Stanbridge Station",
    		"Stanstead",
    		"Stanstead",
    		"Stanstead-Est",
    		"Stoke",
    		"Stoneham-et-Tewkesbury",
    		"Stornoway",
    		"Stratford",
    		"Stukely-Sud",
    		"Sutton",
    		"Tadoussac",
    		"Taschereau",
    		"Témiscaming",
    		"Témiscouata-sur-le-Lac",
    		"Terrasse-Vaudreuil",
    		"Terrebonne",
    		"Thetford Mines",
    		"Thorne",
    		"Thurso",
    		"Tingwick",
    		"Tourville",
    		"Trécesson",
    		"Très-Saint-Rédempteur",
    		"Très-Saint-Sacrement",
    		"Tring-Jonction",
    		"Trois-Pistoles",
    		"Trois-Rives",
    		"Trois-Rivières",
    		"Ulverton",
    		"Upton",
    		"Val-Alain",
    		"Val-Brillant",
    		"Val-David",
    		"Val-des-Bois",
    		"Val-des-Lacs",
    		"Val-des-Monts",
    		"Val-d'Or",
    		"Val-Joli",
    		"Val-Morin",
    		"Val-Racine",
    		"Val-Saint-Gilles",
    		"Valcourt",
    		"Valcourt",
    		"Vallée-Jonction",
    		"Varennes",
    		"Vaudreuil-Dorion",
    		"Vaudreuil-sur-le-Lac",
    		"Venise-en-Québec",
    		"Verchères",
    		"Victoriaville",
    		"Ville-Marie",
    		"Villeroy",
    		"Waltham",
    		"Warden",
    		"Warwick",
    		"Waterloo",
    		"Waterville",
    		"Weedon",
    		"Wentworth",
    		"Wentworth-Nord",
    		"Westbury",
    		"Westmount",
    		"Wickham",
    		"Windsor",
    		"Wotton",
    		"Yamachiche",
    		"Yamaska"};


    		String[] namesNB = new String[]{
    		"Bathurst",
    		"Campbellton",
    		"Dieppe",
    		"Edmundston",
    		"Fredericton",
    		"Miramichi",
    		"Moncton",
    		"Saint John",
    		"Beresford",
    		"Bouctouche",
    		"Caraquet",
    		"Dalhousie",
    		"Florenceville-Bristol",
    		"Grand Bay-Westfield",
    		"Grand Falls",
    		"Hampton",
    		"Hartland",
    		"Lamèque",
    		"Nackawic",
    		"Oromocto",
    		"Quispamsis",
    		"Richibucto",
    		"Riverview",
    		"Rothesay",
    		"Sackville",
    		"Saint Andrews",
    		"St. George",
    		"Saint-Léonard",
    		"Saint-Quentin",
    		"St. Stephen",
    		"Shediac",
    		"Shippagan",
    		"Sussex",
    		"Woodstock",
    		"Alma",
    		"Aroostook",
    		"Atholville",
    		"Balmoral",
    		"Bas-Caraquet",
    		"Bath",
    		"Belledune",
    		"Bertrand",
    		"Blacks Harbour",
    		"Blackville",
    		"Cambridge-Narrows",
    		"Canterbury",
    		"Cap-Pelé",
    		"Centreville",
    		"Charlo",
    		"Chipman",
    		"Doaktown",
    		"Dorchester",
    		"Drummond",
    		"Eel River Crossing",
    		"Fredericton Junction",
    		"Gagetown",
    		"Grand Manan",
    		"Grande-Anse",
    		"Harvey",
    		"Hillsborough",
    		"Lac Baker",
    		"Le Goulet",
    		"Maisonnette",
    		"McAdam",
    		"Meductic",
    		"Memramcook",
    		"Millville",
    		"Minto",
    		"Neguac",
    		"New Maryland",
    		"Nigadoo",
    		"Norton",
    		"Paquetville",
    		"Perth-Andover",
    		"Petitcodiac",
    		"Petit-Rocher",
    		"Plaster Rock",
    		"Pointe-Verte",
    		"Port Elgin",
    		"Rexton",
    		"Riverside-Albert",
    		"Rivière-Verte",
    		"Rogersville",
    		"Sainte-Anne-de-Madawaska",
    		"Saint-Antoine",
    		"Saint-Isidore",
    		"Saint-Léolin",
    		"Saint-Louis de Kent",
    		"Sainte-Marie-Saint-Raphaël",
    		"St. Martins",
    		"Salisbury",
    		"Stanley",
    		"Sussex Corner",
    		"Tide Head",
    		"Tracy",
    		"Tracadie",
    		"Beaubassin East",
    		"Campobello Island",
    		"Cocagne",
    		"Hanwell",
    		"Haut-Madawaska[d]",
    		"Kedgwick[e]",
    		"Saint-André",
    		"Upper Miramichi"};


    		String[] namesNS = new String[]{
    		"Cape Breton",
    		"Halifax",
    		"Queens",
    		"Annapolis",
    		"Antigonish",
    		"Colchester",
    		"Cumberland",
    		"Inverness",
    		"Kings",
    		"Pictou",
    		"Richmond",
    		"Victoria",
    		"Argyle",
    		"Barrington",
    		"Chester",
    		"Clare",
    		"Digby",
    		"East Hants",
    		"Guysborough",
    		"Lunenburg",
    		"Shelburne",
    		"St. Mary's",
    		"West Hants",
    		"Yarmouth",
    		"Amherst",
    		"Annapolis Royal",
    		"Antigonish",
    		"Berwick",
    		"Bridgewater",
    		"Clark's Harbour",
    		"Digby",
    		"Kentville",
    		"Lockeport",
    		"Lunenburg",
    		"Mahone Bay",
    		"Middleton",
    		"Mulgrave",
    		"New Glasgow",
    		"Oxford",
    		"Pictou",
    		"Port Hawkesbury",
    		"Shelburne",
    		"Stellarton",
    		"Stewiacke",
    		"Trenton",
    		"Truro",
    		"Westville",
    		"Windsor",
    		"Wolfville",
    		"Yarmouth"};


    		String[] namesPEI = new String[]{
    		"Charlottetown",
    		"Summerside",
    		"Alberton",
    		"Borden-Carleton",
    		"Cornwall",
    		"Kensington",
    		"North Rustico",
    		"O'Leary",
    		"Souris",
    		"Stratford",
    		"Three Rivers",
    		"Tignish",
    		"Abram-Village",
    		"Afton",
    		"Alexandra",
    		"Annandale-Little Pond-Howe Bay",
    		"Bedeque and Area",
    		"Belfast",
    		"Bonshaw",
    		"Brackley",
    		"Breadalbane",
    		"Central Kings",
    		"Central Prince",
    		"Clyde River",
    		"Crapaud",
    		"Darlington",
    		"Eastern Kings",
    		"Greenmount-Montrose",
    		"Hampshire",
    		"Hazelbrook",
    		"Hunter River",
    		"Kingston",
    		"Kinkora",
    		"Linkletter",
    		"Lot 11 and Area",
    		"Malpeque Bay",
    		"Meadowbank",
    		"Miltonvale Park",
    		"Miminegash",
    		"Miscouche",
    		"Morell",
    		"Mount Stewart",
    		"Murray Harbour",
    		"Murray River",
    		"New Haven-Riverdale",
    		"North Shore",
    		"North Wiltshire",
    		"Northport",
    		"Sherbrooke",
    		"Souris West",
    		"St. Felix",
    		"St. Louis",
    		"St. Nicholas",
    		"St. Peters Bay",
    		"Tignish Shore",
    		"Tyne Valley",
    		"Union Road",
    		"Victoria",
    		"Warren Grove",
    		"Wellington",
    		"West River",
    		"York"};


    		String[] namesNFLD = new String[]{
    		"Corner Brook",
    		"Mount Pearl",
    		"St. John's",
    		"Admirals Beach",
    		"Anchor Point",
    		"Appleton",
    		"Aquaforte",
    		"Arnold's Cove",
    		"Avondale",
    		"Badger",
    		"Baie Verte",
    		"Baine Harbour",
    		"Bauline",
    		"Bay Bulls",
    		"Bay de Verde",
    		"Bay L'Argent",
    		"Bay Roberts",
    		"Baytona",
    		"Beachside",
    		"Bellburns",
    		"Belleoram",
    		"Birchy Bay",
    		"Bird Cove",
    		"Bishop's Cove",
    		"Bishop's Falls",
    		"Bonavista",
    		"Botwood",
    		"Branch",
    		"Brent's Cove",
    		"Brighton",
    		"Brigus",
    		"Bryant's Cove",
    		"Buchans",
    		"Burgeo",
    		"Burin",
    		"Burlington",
    		"Burnt Islands",
    		"Campbellton",
    		"Cape Broyle",
    		"Cape St. George",
    		"Carbonear",
    		"Carmanville",
    		"Cartwright",
    		"Centreville-Wareham-Trinity",
    		"Chance Cove",
    		"Change Islands",
    		"Channel-Port aux Basques",
    		"Chapel Arm",
    		"Charlottetown (Labrador)",
    		"Clarenville",
    		"Clarke's Beach",
    		"Coachman's Cove",
    		"Colinet",
    		"Colliers",
    		"Come By Chance",
    		"Comfort Cove-Newstead",
    		"Conception Bay South",
    		"Conception Harbour",
    		"Conche",
    		"Cook's Harbour",
    		"Cormack",
    		"Cottlesville",
    		"Cow Head",
    		"Cox's Cove",
    		"Crow Head",
    		"Cupids",
    		"Daniel's Harbour",
    		"Deer Lake",
    		"Dover",
    		"Duntara",
    		"Eastport",
    		"Elliston",
    		"Embree",
    		"Englee",
    		"English Harbour East",
    		"Fermeuse",
    		"Ferryland",
    		"Flatrock",
    		"Fleur de Lys",
    		"Flower's Cove",
    		"Fogo Island",
    		"Forteau",
    		"Fortune",
    		"Fox Cove-Mortier",
    		"Fox Harbour",
    		"Frenchman's Cove",
    		"Gallants",
    		"Gambo",
    		"Gander",
    		"Garnish",
    		"Gaskiers-Point La Haye",
    		"Gaultois",
    		"Gillams",
    		"Glenburnie-Birchy Head-Shoal Brook",
    		"Glenwood",
    		"Glovertown",
    		"Goose Cove East",
    		"Grand Bank",
    		"Grand Falls-Windsor",
    		"Grand le Pierre",
    		"Greenspond",
    		"Hampden",
    		"Hant's Harbour",
    		"Happy Adventure",
    		"Happy Valley-Goose Bay",
    		"Harbour Breton",
    		"Harbour Grace",
    		"Harbour Main-Chapel's Cove-Lakeview",
    		"Hare Bay",
    		"Hawke's Bay",
    		"Heart's Content",
    		"Heart's Delight-Islington",
    		"Heart's Desire",
    		"Hermitage-Sandyville",
    		"Holyrood",
    		"Hopedale",
    		"Howley",
    		"Hughes Brook",
    		"Humber Arm South",
    		"Indian Bay",
    		"Irishtown-Summerside",
    		"Isle aux Morts",
    		"Jackson's Arm",
    		"Keels",
    		"King's Cove",
    		"King's Point",
    		"Kippens",
    		"Labrador City",
    		"Lamaline",
    		"L'Anse-au-Loup",
    		"L'Anse-au-Clair",
    		"Lark Harbour",
    		"LaScie",
    		"Lawn",
    		"Leading Tickles",
    		"Lewin's Cove",
    		"Lewisporte",
    		"Little Bay",
    		"Little Bay East",
    		"Little Bay Islands",
    		"Little Burnt Bay",
    		"Logy Bay-Middle Cove-Outer Cove",
    		"Long Harbour-Mount Arlington Heights",
    		"Lord's Cove",
    		"Lourdes",
    		"Lumsden",
    		"Lushes Bight-Beaumont-Beaumont North",
    		"Main Brook",
    		"Makkovik",
    		"Mary's Harbour",
    		"Marystown",
    		"Massey Drive",
    		"McIvers",
    		"Meadows",
    		"Middle Arm",
    		"Miles Cove",
    		"Millertown",
    		"Milltown-Head of Bay d'Espoir",
    		"Ming's Bight",
    		"Morrisville",
    		"Mount Carmel-Mitchells Brook-St. Catherines",
    		"Mount Moriah",
    		"Musgrave Harbour",
    		"Musgravetown",
    		"Nain",
    		"New Perlican",
    		"New-Wes-Valley",
    		"Nipper's Harbour",
    		"Norman's Cove-Long Cove",
    		"Norris Arm",
    		"Norris Point",
    		"North River",
    		"North West River",
    		"Northern Arm",
    		"Old Perlican",
    		"Pacquet",
    		"Paradise",
    		"Parkers Cove",
    		"Parson's Pond",
    		"Pasadena",
    		"Peterview",
    		"Petty Harbour-Maddox Cove",
    		"Pilley's Island",
    		"Pinware",
    		"Placentia",
    		"Point au Gaul",
    		"Point Lance",
    		"Point Leamington",
    		"Point May",
    		"Point of Bay",
    		"Pool's Cove",
    		"Port Anson",
    		"Port au Choix",
    		"Port au Port East",
    		"Port au Port West-Aguathuna-Felix Cove",
    		"Port Blandford",
    		"Port Hope Simpson",
    		"Port Kirwan",
    		"Port Rexton",
    		"Port Saunders",
    		"Portugal Cove South",
    		"Portugal Cove-St. Philip's",
    		"Postville",
    		"Pouch Cove",
    		"Raleigh",
    		"Ramea",
    		"Red Bay",
    		"Red Harbour",
    		"Reidville",
    		"Rencontre East",
    		"Renews-Cappahayden",
    		"Rigolet",
    		"River of Ponds",
    		"Riverhead",
    		"Robert's Arm",
    		"Rocky Harbour",
    		"Roddickton-Bide Arm",
    		"Rose Blanche-Harbour le Cou",
    		"Rushoon",
    		"Sally's Cove",
    		"Salmon Cove",
    		"Salvage",
    		"Sandringham",
    		"Sandy Cove",
    		"Seal Cove (Fortune Bay)",
    		"Seal Cove (White Bay)",
    		"Small Point-Adam's Cove-Blackhead-Broad Cove",
    		"South Brook",
    		"South River",
    		"Southern Harbour",
    		"Spaniard's Bay",
    		"Springdale",
    		"St. Alban's",
    		"St. Anthony",
    		"St. Bernard's-Jacques Fontaine",
    		"St. Brendan's",
    		"St. Bride's",
    		"St. George's",
    		"St. Jacques-Coomb's Cove",
    		"St. Joseph's",
    		"St. Lawrence",
    		"St. Lewis",
    		"St. Lunaire-Griquet",
    		"St. Mary's",
    		"St. Pauls",
    		"St. Shott's",
    		"St. Vincent's-St. Stephen's-Peter's River",
    		"Steady Brook",
    		"Stephenville",
    		"Stephenville Crossing",
    		"Summerford",
    		"Sunnyside",
    		"Terra Nova",
    		"Terrenceville",
    		"Tilt Cove",
    		"Torbay",
    		"Traytown",
    		"Trepassey",
    		"Trinity",
    		"Trinity Bay North",
    		"Triton",
    		"Trout River",
    		"Twillingate",
    		"Upper Island Cove",
    		"Victoria",
    		"Wabana",
    		"Wabush",
    		"West St. Modeste",
    		"Westport",
    		"Whitbourne",
    		"Whiteway",
    		"Winterland",
    		"Winterton",
    		"Witless Bay",
    		"Woodstock",
    		"Woody Point",
    		"York Harbour"};


    		String[] namesNWT = new String[]{
    		"Aklavik",
    		"Behchoko`",
    		"Deline",
    		"Enterprise",
    		"Fort Good Hope",
    		"Fort Liard",
    		"Fort McPherson",
    		"Fort Providence",
    		"Fort Resolution",
    		"Fort Simpson",
    		"Fort Smith",
    		"Gamèti",
    		"Hay River",
    		"Inuvik",
    		"Norman Wells",
    		"Paulatuk",
    		"Sachs Harbour",
    		"Tsiigehtchic",
    		"Tuktoyaktuk",
    		"Tulita",
    		"Ulukhaktok",
    		"Wekweeti",
    		"Whatì",
    		"Yellowknife"};


    		String[] namesNU = new String[]{
    		"Arctic Bay",
    		"Arviat",
    		"Baker Lake",
    		"Cambridge Bay",
    		"Cape Dorset",
    		"Chesterfield Inlet",
    		"Clyde River",
    		"Coral Harbour",
    		"Gjoa Haven",
    		"Grise Fiord",
    		"Hall Beach",
    		"Igloolik",
    		"Iqaluit",
    		"Kimmirut",
    		"Kugaaruk",
    		"Kugluktuk",
    		"Naujaat",
    		"Pangnirtung",
    		"Pond Inlet",
    		"Qikiqtarjuaq",
    		"Rankin Inlet",
    		"Resolute",
    		"Sanikiluaq",
    		"Taloyoak",
    		"Whale Cove"};

    		String[] namesYU = new String[]{
    		"Carmacks",
    		"Dawson",
    		"Faro",
    		"Haines Junction",
    		"Mayo",
    		"Teslin",
    		"Watson Lake",
    		"Whitehorse"};
}


